\documentclass{beamer}

\usepackage{verbatim,multicol,amsmath}
\usepackage{animate}

% Theme settings
\usetheme{AnnArbor}\usecolortheme{beaver}
\setbeamertemplate{navigation symbols}{}


% Document settings
\newcommand{\lecturetitle}{Two-way ANOVA}
\title[\lecturetitle]{STAT 401A - Statistical Methods for Research Workers}
\subtitle{\lecturetitle}
\author[Jarad Niemi]{Jarad Niemi (Dr. J)}
\institute[Iowa State]{Iowa State University}
\date[\today]{last updated: \today}

\setkeys{Gin}{width=0.6\textwidth}
\newenvironment{remark}[1][Remark]{\begin{trivlist}
\item[\hskip \labelsep {\bfseries #1}]}{\end{trivlist}}

\newcommand{\I}{\mathrm{I}}
\newcommand{\J}{\mathrm{J}}

<<options, echo=FALSE, warning=FALSE, message=FALSE>>=
options(width=120)
opts_chunk$set(comment=NA, 
               fig.width=6, fig.height=5, 
               size='tiny', 
               out.width='0.8\\textwidth', 
               fig.align='center', 
               message=FALSE,
               echo=FALSE)
library(plyr)
library(ggplot2)
library(xtable)
library(Sleuth3)
library(reshape2)
@


\begin{document}

\begin{frame}
\maketitle
\end{frame}

\section{Two-way ANOVA}


\frame{\frametitle{Data}
  An experiment was run on tomato plants to determine the effect of 
	\begin{itemize}
	\item 3 different varieties (A,B,C) \pause and 
	\item 4 different planting densities (10,20,30,40) \pause 
	\end{itemize}
	on yield. 
	
	\vspace{0.2in} \pause 
	
	There is an expectation that planting density will have a different effect depending on the variety. \pause Therefore a \alert{balanced, complete, randomized} design was used. \pause 
	\begin{itemize}\small
	\item complete: each treatment (variety $\times$ density) is represented in the experiment \pause
	\item balanced: each treatment in the experiment has the same number of replications \pause
	\item randomized: treatment was randomly assigned to the plot \pause
	\end{itemize}
	This is also referred to as a \alert{full factorial} or \alert{fully crossed} design.
}

\frame{\frametitle{Hypotheses}
	\begin{itemize}
	\item Does variety affect mean yield?
		\begin{itemize}
		\item<4-> Is the mean yield for variety A different from B \alert{on average}?
		\item<5-> Is the mean yield for variety A different from B \alert{at a particular value for density}?
		\end{itemize}
	\item<2-> Does density affect mean yield?
		\begin{itemize}
		\item<6-> Is the mean yield for density 10 different from density 20 \alert{on average}?
		\item<7-> Is the mean yield for density 10 different from density 20 \alert{at a particular value for variety}?
		\end{itemize}
	\item<3-> Does density affect yield differently for each variety?
	\end{itemize}
	
	\vspace{0.2in} 
	
	\uncover<8->{For all of these questions, we want to know
	\begin{itemize}
	\item is there any effect and 
	\item if yes, what is the nature of the effect.
	\end{itemize}}
	\uncover<9->{Confidence intervals can answer these questions. }
}

\begin{frame}[fragile]
<<>>=
tomato = read.csv("Ch13-tomato.csv")
ggplot(tomato, aes(x=Density, y=Yield, color=Variety)) + geom_point()
@
\end{frame}

\begin{frame}[fragile]
\frametitle{Summary statistics}

<<>>=
sm = 
ddply(tomato, .(Variety, Density), summarize, 
      n    = length(Yield),
      mean = mean(Yield),
      sd   = sd(Yield))
@

Number of replicates
<<>>=
dcast(sm[,c("Variety","Density","n")], Variety~Density, value.var="n")
@

Mean Yield 
<<>>=
dcast(sm[,c("Variety","Density","mean")], Variety~Density, value.var="mean")
@

Standard deviation of yield
<<>>=
dcast(sm[,c("Variety","Density","sd")], Variety~Density, value.var="sd")
@

\end{frame}

\frame{\frametitle{Two-way ANOVA}
	\begin{itemize}[<+->]
	\item Setup: Two categorical explanatory variables with $\I$ and $\J$ levels
	\item Model:
	\[ Y_{ijk} \stackrel{ind}{\sim} N(\mu_{ij},\sigma^2) \]
	where $Y_{ijk}$ is the 
	\begin{itemize}
	\item $k$th observation at the 
	\item $i$th level of variable 1 (variety) with $i=1,\ldots,\I$ and the 
	\item $j$th level of variable 2 (density) with $j=1,\ldots,\J$.
	\end{itemize}
	
	\vspace{0.2in} \pause 
	
	Consider the models:
		\begin{itemize}
		\item Additive: $\mu_{ij} = \mu+\alpha_i + \eta_j$
		\item Cell-means: $\mu_{ij} = \mu+\alpha_i + \eta_j + \gamma_{ij}$
		\end{itemize}
	\end{itemize}
	\pause
	\[ \begin{array}{|c|c|c|c|c|}
	\hline
	& 10 & 20 & 30 & 40 \\
	\hline
	\mbox{A} & \mu_{11} & \mu_{12} & \mu_{13} & \mu_{14} \\
	\hline
	\mbox{B} & \mu_{21} & \mu_{22} & \mu_{23} & \mu_{24} \\
	\hline
	\mbox{C} & \mu_{31} & \mu_{32} & \mu_{33} & \mu_{34} \\
	\hline
	\end{array} \]
}

\frame{\frametitle{As a regression model}
	\begin{enumerate}[<+->]
	\item Assign a reference level for both variety (C) and density (40).
	\item Let $V_i$ and $D_i$ be the variety and density for observation $i$. 
	\item Build indicator variables, e.g. $\I(V_i=A)$ and $\I(D_i=10)$. 
	\item The additive model: {\scriptsize
	\[ \begin{array}{rl} \mu_{i} =& \beta_0 + \beta_1\I(V_i=A) + \beta_2\I(V_i=B) \\
	&+ \beta_3\I(D_i=10)+\beta_4\I(D_i=20)+\beta_5\I(D_i=30).
	\end{array} \]
	$\beta_1$ is the expected difference in yield between varieties A and C at any fixed density}
	\item The cell-means model:{\scriptsize
	\[ \begin{array}{rl} \mu_{i} =& \beta_0 + \beta_1\I(V_i=A) + \beta_2\I(V_i=B) \\
	&+ \beta_3\I(D_i=10)+\beta_4\I(D_i=20)+\beta_5\I(D_i=30) \\ \\
	&+\beta_6\I(V_i=A)\I(D_i=10)+\beta_7\I(V_i=A)\I(D_i=20)+\beta_8\I(V_i=A)\I(D_i=30) \\
	&+\beta_9\I(V_i=B)\I(D_i=10)+\beta_{10}\I(V_i=B)\I(D_i=20)+\beta_{11}\I(V_i=B)\I(D_i=30) \\
	\end{array} \]
	$\beta_1$ is the expected difference in yield between varieties A and C at a density of 40}
	\end{enumerate}
}


% Table for means using regresison model


\subsection{ANOVA Table}
\begin{frame}
\frametitle{ANOVA Table}

ANOVA Table - Additive model
\begin{center}
\begin{tabular}{ccccc}
Source & SS & df & MS & F \\
\hline
Factor A & SSA & ($\I$-1) & SSA/($\I$-1) & MSA/MSE\\
Factor B & SSB & ($\J$-1) & SSB/($\J$-1) & MSB/MSE \\
Error & SSE & n-$\I$-$\J$+1 & SSE/(n-$\I$-$\J$+1) \\
Total & SST & n-$1$ 
\end{tabular}
\end{center}

\vspace{0.2in} \pause

ANOVA Table - Cell-means model
\begin{center}
\begin{tabular}{ccccc}
Source & SS & df & MS & \\
\hline
Factor A & SSA & $\I$-1 & SSA/($\I$-1) & MSA/MSE \\
Factor B & SSB & $\J$-1 & SSB/($\J$-1) & MSB/MSE \\
Interaction AB & SSAB & ($\I$-1)($\J$-1) & SSAB /($\I$-1)($\J$-1) & MSAB/MSE \\
Error & SSE & n-$\I$$\J$ & SSE/(n-$\I$$\J$) \\
Total & SST & n-$1$ 
\end{tabular}
\end{center}

\end{frame}



\subsection{Additive vs cell-means}
\begin{frame}
\frametitle{Additive vs cell-means}

Opinions differ on whether to use an additive vs a cell-means model when the interaction is not significant. \pause Remember that an insignificant test does not prove that there is no interaction. 

\vspace{0.2in} \pause

\begin{center}
\begin{tabular}{lcc}
& Additive & Cell-means \\
\hline
Interpretation & Direct & Complicated \\
Estimate of $\sigma^2$ & Biased & Unbiased
\end{tabular}
\end{center}

\vspace{0.2in} \pause

We will continue using the cell-means model to answer the scientific questions of interest.

\end{frame}



\subsection{PROC GLM}
\frame[containsverbatim]{\frametitle{Two-way ANOVA using PROC GLM}
\begin{verbatim}
DATA tomato;
  INFILE 'Ch13-tomato.csv' DSD FIRSTOBS=2;
  INPUT variety $ density yield;

PROC GLM DATA=tomato PLOTS=all;
  CLASS variety density;
  MODEL yield = variety|density / SOLUTION;
  LSMEANS variety / cl adjust=tukey;
  LSMEANS density / cl adjust=tukey;
  LSMEANS variety*density / cl adjust=tukey;
  RUN;
\end{verbatim}
}

\frame[containsverbatim]{\frametitle{Two-way ANOVA using PROC GLM}
{\tiny
\begin{verbatim}
                                        The GLM Procedure

Dependent Variable: yield

                                               Sum of
       Source                      DF         Squares     Mean Square    F Value    Pr > F
       Model                       11     422.3155556      38.3923232      24.22    <.0001
       Error                       24      38.0400000       1.5850000
       Corrected Total             35     460.3555556

                       R-Square     Coeff Var      Root MSE    yield Mean
                       0.917368      9.064568      1.258968      13.88889

       Source                      DF       Type I SS     Mean Square    F Value    Pr > F
       variety                      2     327.5972222     163.7986111     103.34    <.0001
       density                      3      86.6866667      28.8955556      18.23    <.0001
       variety*density              6       8.0316667       1.3386111       0.84    0.5484

       Source                      DF     Type III SS     Mean Square    F Value    Pr > F
       variety                      2     327.5972222     163.7986111     103.34    <.0001
       density                      3      86.6866667      28.8955556      18.23    <.0001
       variety*density              6       8.0316667       1.3386111       0.84    0.5484
\end{verbatim}
}

The Type I and Type III SS are equal because the design is balanced.
}

\frame[containsverbatim]{\frametitle{Two-way ANOVA using PROC GLM}
{\tiny
\begin{verbatim}
MODEL yield = variety|density / SOLUTION;
                                        The GLM Procedure

                                                        Standard
         Parameter                    Estimate             Error    t Value    Pr > |t|

         Intercept                 18.16666667 B      0.72686542      24.99      <.0001
         variety         A         -7.36666667 B      1.02794293      -7.17      <.0001
         variety         B         -5.40000000 B      1.02794293      -5.25      <.0001
         variety         C          0.00000000 B       .                .         .    
         density         10        -1.86666667 B      1.02794293      -1.82      0.0819
         density         20        -0.06666667 B      1.02794293      -0.06      0.9488
         density         30         1.76666667 B      1.02794293       1.72      0.0986
         density         40         0.00000000 B       .                .         .    
         variety*density A 10       0.26666667 B      1.45373083       0.18      0.8560
         variety*density A 20       1.70000000 B      1.45373083       1.17      0.2537
         variety*density A 30       0.33333333 B      1.45373083       0.23      0.8206
         variety*density A 40       0.00000000 B       .                .         .    
         variety*density B 10      -1.96666667 B      1.45373083      -1.35      0.1887
         variety*density B 20      -0.06666667 B      1.45373083      -0.05      0.9638
         variety*density B 30      -0.03333333 B      1.45373083      -0.02      0.9819
         variety*density B 40       0.00000000 B       .                .         .    
         variety*density C 10       0.00000000 B       .                .         .    
\end{verbatim}
}
}

\begin{frame}[fragile]
<<>>=
ggplot(sm, aes(x=Density, y=mean, col=Variety)) + geom_line() +labs(y="Mean Yield")
@
\end{frame}





\frame[containsverbatim]{\frametitle{Is the mean yield for variety A different from B \alert{on average}?}
{\tiny
\begin{verbatim}
LSMEANS variety / cl adjust=tukey;
                                       Least Squares Means
                           Adjustment for Multiple Comparisons: Tukey

...

                             Least Squares Means for effect variety
                              Pr > |t| for H0: LSMean(i)=LSMean(j)

                                   Dependent Variable: yield

                         i/j              1             2             3
                            1                      0.2249        <.0001
                            2        0.2249                      <.0001
                            3        <.0001        <.0001

                      variety    yield LSMEAN      95% Confidence Limits
                      A             11.333333       10.583245    12.083422
                      B             12.208333       11.458245    12.958422
                      C             18.125000       17.374912    18.875088

                              Least Squares Means for Effect variety
                                   Difference         Simultaneous 95%
                                      Between      Confidence Limits for
                       i    j           Means       LSMean(i)-LSMean(j)
                       1    2       -0.875000       -2.158534     0.408534
                       1    3       -6.791667       -8.075201    -5.508132
                       2    3       -5.916667       -7.200201    -4.633132
\end{verbatim}
}
}





\frame[containsverbatim]{\frametitle{Is the mean yield at density 10 different from density 20 \alert{on average}?}
{\tiny
\begin{verbatim}
LSMEANS density / cl adjust=tukey;
                                       Least Squares Means
                           Adjustment for Multiple Comparisons: Tukey
                                        ...

                      density    yield LSMEAN      95% Confidence Limits
                      10            11.477778       10.611650    12.343905
                      20            14.388889       13.522762    15.255016
                      30            15.777778       14.911650    16.643905
                      40            13.911111       13.044984    14.777238

                              Least Squares Means for Effect density
                                   Difference         Simultaneous 95%
                                      Between      Confidence Limits for
                       i    j           Means       LSMean(i)-LSMean(j)

                       1    2       -2.911111       -4.548299    -1.273923
                       1    3       -4.300000       -5.937188    -2.662812
                       1    4       -2.433333       -4.070521    -0.796145
                       2    3       -1.388889       -3.026077     0.248299
                       2    4        0.477778       -1.159410     2.114966
                       3    4        1.866667        0.229479     3.503855
\end{verbatim}
}
}



\frame[containsverbatim]{\frametitle{Is mean yield different for particular combinations?}
{\tiny
\begin{verbatim}
LSMEANS variety*density / cl adjust=tukey;

                 variety    density    yield LSMEAN      95% Confidence Limits

                 A          10             9.200000        7.699824    10.700176
                 A          20            12.433333       10.933157    13.933510
                 A          30            12.900000       11.399824    14.400176
                 A          40            10.800000        9.299824    12.300176
                 B          10             8.933333        7.433157    10.433510
                 B          20            12.633333       11.133157    14.133510
                 B          30            14.500000       12.999824    16.000176
                 B          40            12.766667       11.266490    14.266843
                 C          10            16.300000       14.799824    17.800176
                 C          20            18.100000       16.599824    19.600176
                 C          30            19.933333       18.433157    21.433510
                 C          40            18.166667       16.666490    19.666843
\end{verbatim}
}
}



\frame[containsverbatim]{\frametitle{Is mean yield different for particular combinations?}
{\tiny
\begin{verbatim}
LSMEANS variety*density / cl adjust=tukey;

                          Least Squares Means for Effect variety*density
 
                                    Difference         Simultaneous 95%
                                       Between      Confidence Limits for
                       i     j           Means       LSMean(i)-LSMean(j)
                       1     2       -3.233333       -6.939704     0.473037
                       1     3       -3.700000       -7.406371     0.006371
                       1     4       -1.600000       -5.306371     2.106371
                       1     5        0.266667       -3.439704     3.973037
                       1     6       -3.433333       -7.139704     0.273037
                       1     7       -5.300000       -9.006371    -1.593629
                       1     8       -3.566667       -7.273037     0.139704
                       1     9       -7.100000      -10.806371    -3.393629
                       1    10       -8.900000      -12.606371    -5.193629
                       1    11      -10.733333      -14.439704    -7.026963
                       1    12       -8.966667      -12.673037    -5.260296
                       2     3       -0.466667       -4.173037     3.239704
                       2     4        1.633333       -2.073037     5.339704
                       2     5        3.500000       -0.206371     7.206371
                       2     6       -0.200000       -3.906371     3.506371
                       2     7       -2.066667       -5.773037     1.639704
                       2     8       -0.333333       -4.039704     3.373037
                       2     9       -3.866667       -7.573037    -0.160296
                       2    10       -5.666667       -9.373037    -1.960296
                       2    11       -7.500000      -11.206371    -3.793629
                       2    12       -5.733333       -9.439704    -2.026963
                       3     4        2.100000       -1.606371     5.806371
                       3     5        3.966667        0.260296     7.673037
                       3     6        0.266667       -3.439704     3.973037
                       3     7       -1.600000       -5.306371     2.106371
                       3     8        0.133333       -3.573037     3.839704
                       3     9       -3.400000       -7.106371     0.306371
                       3    10       -5.200000       -8.906371    -1.493629
                       3    11       -7.033333      -10.739704    -3.326963
                       3    12       -5.266667       -8.973037    -1.560296
                       4     5        1.866667       -1.839704     5.573037
                       4     6       -1.833333       -5.539704     1.873037
                       4     7       -3.700000       -7.406371     0.006371
                       4     8       -1.966667       -5.673037     1.739704
                       4     9       -5.500000       -9.206371    -1.793629
                       4    10       -7.300000      -11.006371    -3.593629
                       4    11       -9.133333      -12.839704    -5.426963
                       4    12       -7.366667      -11.073037    -3.660296
                       5     6       -3.700000       -7.406371     0.006371
                       5     7       -5.566667       -9.273037    -1.860296
                       5     8       -3.833333       -7.539704    -0.126963
                       5     9       -7.366667      -11.073037    -3.660296
                       5    10       -9.166667      -12.873037    -5.460296
                       5    11      -11.000000      -14.706371    -7.293629
                       5    12       -9.233333      -12.939704    -5.526963
                       6     7       -1.866667       -5.573037     1.839704
                       6     8       -0.133333       -3.839704     3.573037
                       6     9       -3.666667       -7.373037     0.039704
                       6    10       -5.466667       -9.173037    -1.760296
                       6    11       -7.300000      -11.006371    -3.593629
                       6    12       -5.533333       -9.239704    -1.826963
                       7     8        1.733333       -1.973037     5.439704
                       7     9       -1.800000       -5.506371     1.906371
                       7    10       -3.600000       -7.306371     0.106371
                       7    11       -5.433333       -9.139704    -1.726963
                       7    12       -3.666667       -7.373037     0.039704
                       8     9       -3.533333       -7.239704     0.173037
                       8    10       -5.333333       -9.039704    -1.626963
                       8    11       -7.166667      -10.873037    -3.460296
                       8    12       -5.400000       -9.106371    -1.693629
                       9    10       -1.800000       -5.506371     1.906371
                       9    11       -3.633333       -7.339704     0.073037
                       9    12       -1.866667       -5.573037     1.839704
                      10    11       -1.833333       -5.539704     1.873037
                      10    12       -0.066667       -3.773037     3.639704
                      11    12        1.766667       -1.939704     5.473037
\end{verbatim}
}
}


\subsection{Analysis in R}
\begin{frame}[fragile]
\frametitle{}
<<echo=TRUE>>=
tomato = read.csv("Ch13-tomato.csv")
tomato$Density = factor(tomato$Density)
m = lm(Yield~Variety*Density, tomato)
anova(m)
@
\end{frame}

\begin{frame}[fragile]
\frametitle{}
<<echo=TRUE>>=
library(lsmeans)
lsmeans(m, pairwise~Variety)
@
\end{frame}

\begin{frame}[fragile]
\frametitle{}
<<echo=TRUE>>=
lsmeans(m, pairwise~Density)
@
\end{frame}


\begin{frame}[fragile]
\frametitle{}
<<echo=TRUE>>=
lsmeans(m, pairwise~Variety*Density)
@
\end{frame}


\section{Summary}
\frame{\frametitle{Summary}
	\begin{itemize}[<+->]
	\item Use LSMEANS to answer questions of scientific interest.
	\item Check model assumptions
	\item Consider alternative models, e.g. treating density as continuous 
	\end{itemize}
}


\end{document}