\documentclass[handout]{beamer}

\usepackage{verbatim,multicol,amsmath}
\usepackage{animate}

% Theme settings
\usetheme{AnnArbor}\usecolortheme{beaver}
\setbeamertemplate{navigation symbols}{}


% Document settings
\newcommand{\lecturetitle}{Two-way ANOVA}
\title[\lecturetitle]{STAT 401A - Statistical Methods for Research Workers}
\subtitle{\lecturetitle}
\author[Jarad Niemi]{Jarad Niemi (Dr. J)}
\institute[Iowa State]{Iowa State University}
\date[\today]{last updated: \today}

\setkeys{Gin}{width=0.6\textwidth}
\newenvironment{remark}[1][Remark]{\begin{trivlist}
\item[\hskip \labelsep {\bfseries #1}]}{\end{trivlist}}

\newcommand{\I}{\mathrm{I}}
\newcommand{\J}{\mathrm{J}}

<<options, echo=FALSE, warning=FALSE, message=FALSE>>=
options(width=120)
opts_chunk$set(comment=NA, 
               fig.width=6, fig.height=5, 
               size='tiny', 
               out.width='0.8\\textwidth', 
               fig.align='center', 
               message=FALSE,
               echo=FALSE)
library(plyr)
library(ggplot2)
library(gridExtra)
library(xtable)
library(Sleuth3)
library(reshape2)
@


\begin{document}

\begin{frame}
\maketitle
\end{frame}

\section{Two-way ANOVA}


\frame{\frametitle{Data}
  An experiment was run on tomato plants to determine the effect of 
	\begin{itemize}
	\item 3 different varieties (A,B,C) \pause and 
	\item 4 different planting densities (10,20,30,40) \pause 
	\end{itemize}
	on yield. 
	
	\vspace{0.2in} \pause 
	
	There is an expectation that planting density will have a different effect depending on the variety. \pause Therefore a \alert{balanced, complete, randomized} design was used. \pause 
	\begin{itemize}\small
	\item complete: each treatment (variety $\times$ density) is represented in the experiment \pause
	\item balanced: each treatment in the experiment has the same number of replications \pause
	\item randomized: treatment was randomly assigned to the plot \pause
	\end{itemize}
	This is also referred to as a \alert{full factorial} or \alert{fully crossed} design.
}

\frame{\frametitle{Hypotheses}
	\begin{itemize}
	\item Does variety affect mean yield?
		\begin{itemize}
		\item<4-> Is the mean yield for variety A different from B \alert{on average}?
		\item<5-> Is the mean yield for variety A different from B \alert{at a particular value for density}?
		\end{itemize}
	\item<2-> Does density affect mean yield?
		\begin{itemize}
		\item<6-> Is the mean yield for density 10 different from density 20 \alert{on average}?
		\item<7-> Is the mean yield for density 10 different from density 20 \alert{at a particular value for variety}?
		\end{itemize}
	\item<3-> Does density affect yield differently for each variety?
	\end{itemize}
	
	\vspace{0.2in} 
	
	\uncover<8->{For all of these questions, we want to know
	\begin{itemize}
	\item is there any effect and 
	\item if yes, what is the nature of the effect.
	\end{itemize}}
	\uncover<9->{Confidence intervals can answer these questions. }
}

\begin{frame}[fragile]
<<>>=
tomato = read.csv("Ch13-tomato.csv")
tomato$Variety = relevel(tomato$Variety, ref="C")
ggplot(tomato, aes(x=Density, y=Yield, color=Variety)) + geom_point()
@
\end{frame}

\begin{frame}[fragile]
\frametitle{Summary statistics}

Number of replicates
<<>>=
dcast(tomato, Variety~Density, value.var="Yield", fun=length)
@

Mean Yield 
<<>>=
dcast(tomato, Variety~Density, value.var="Yield", fun=mean)
@

Standard deviation of yield
<<>>=
dcast(tomato, Variety~Density, value.var="Yield", fun=sd)
@

\end{frame}

\frame{\frametitle{Two-way ANOVA}
	\begin{itemize}[<+->]
	\item Setup: Two categorical explanatory variables with $\I$ and $\J$ levels
	\item Model:
	\[ Y_{ijk} \stackrel{ind}{\sim} N(\mu_{ij},\sigma^2) \]
	where $Y_{ijk}$ is the 
	\begin{itemize}
	\item $k$th observation at the 
	\item $i$th level of variable 1 (variety) with $i=1,\ldots,\I$ and the 
	\item $j$th level of variable 2 (density) with $j=1,\ldots,\J$.
	\end{itemize}
	
	\vspace{0.2in} \pause 
	
	Consider the models:
		\begin{itemize}
		\item Additive: $\mu_{ij} = \mu+\nu_i + \delta_j$
		\item Cell-means: $\mu_{ij} = \mu+\nu_i + \delta_j + \gamma_{ij}$
		\end{itemize}
	\end{itemize}
	\pause
	\[ \begin{array}{|c|c|c|c|c|}
	\hline
	& 10 & 20 & 30 & 40 \\
	\hline
	\mbox{A} & \mu_{11} & \mu_{12} & \mu_{13} & \mu_{14} \\
	\hline
	\mbox{B} & \mu_{21} & \mu_{22} & \mu_{23} & \mu_{24} \\
	\hline
	\mbox{C} & \mu_{31} & \mu_{32} & \mu_{33} & \mu_{34} \\
	\hline
	\end{array} \]
}

\frame{\frametitle{As a regression model}
	\begin{enumerate}[<+->]
	\item Assign a reference level for both variety (C) and density (40).
	\item Let $V_i$ and $D_i$ be the variety and density for observation $i$. 
	\item Build indicator variables, e.g. $\I(V_i=A)$ and $\I(D_i=10)$. 
	\item The additive model: {\scriptsize
	\[ \begin{array}{rl} \mu_{i} =& \beta_0 + \beta_1\I(V_i=A) + \beta_2\I(V_i=B) \\
	&+ \beta_3\I(D_i=10)+\beta_4\I(D_i=20)+\beta_5\I(D_i=30).
	\end{array} \]
	$\beta_1$ is the expected difference in yield between varieties A and C at any fixed density}
	\item The cell-means model:{\scriptsize
	\[ \begin{array}{rl} \mu_{i} =& \beta_0 + \beta_1\I(V_i=A) + \beta_2\I(V_i=B) \\
	&+ \beta_3\I(D_i=10)+\beta_4\I(D_i=20)+\beta_5\I(D_i=30) \\ \\
	&+\beta_6\I(V_i=A)\I(D_i=10)+\beta_7\I(V_i=A)\I(D_i=20)+\beta_8\I(V_i=A)\I(D_i=30) \\
	&+\beta_9\I(V_i=B)\I(D_i=10)+\beta_{10}\I(V_i=B)\I(D_i=20)+\beta_{11}\I(V_i=B)\I(D_i=30) \\
	\end{array} \]
	$\beta_1$ is the expected difference in yield between varieties A and C at a density of 40}
	\end{enumerate}
}


% Table for means using regresison model


\subsection{ANOVA Table}
\begin{frame}
\frametitle{ANOVA Table}

ANOVA Table - Additive model
\begin{center}
\begin{tabular}{ccccc}
Source & SS & df & MS & F \\
\hline
Factor A & SSA & ($\I$-1) & SSA/($\I$-1) & MSA/MSE\\
Factor B & SSB & ($\J$-1) & SSB/($\J$-1) & MSB/MSE \\
Error & SSE & n-$\I$-$\J$-1 & SSE/(n-$\I$-$\J$-1) \\
Total & SST & n-$1$ 
\end{tabular}
\end{center}

\vspace{0.2in} \pause

ANOVA Table - Cell-means model
\begin{center}
\begin{tabular}{ccccc}
Source & SS & df & MS & \\
\hline
Factor A & SSA & $\I$-1 & SSA/($\I$-1) & MSA/MSE \\
Factor B & SSB & $\J$-1 & SSB/($\J$-1) & MSB/MSE \\
Interaction AB & SSAB & ($\I$-1)($\J$-1) & SSAB /($\I$-1)($\J$-1) & MSAB/MSE \\
Error & SSE & n-$\I$$\J$ & SSE/(n-$\I$$\J$) \\
Total & SST & n-$1$ 
\end{tabular}
\end{center}

\end{frame}



\subsection{Additive vs cell-means}
\begin{frame}
\frametitle{Additive vs cell-means}

Opinions differ on whether to use an additive vs a cell-means model when the interaction is not significant. \pause Remember that an insignificant test does not prove that there is no interaction. 

\vspace{0.2in} \pause

\begin{center}
\begin{tabular}{lcc}
& Additive & Cell-means \\
\hline
Interpretation & Direct & Complicated \\
Estimate of $\sigma^2$ & Biased & Unbiased
\end{tabular}
\end{center}

\vspace{0.2in} \pause

We will continue using the cell-means model to answer the scientific questions of interest.

\end{frame}



\subsection{Analysis in SAS}
\frame[containsverbatim]{\frametitle{Two-way ANOVA using PROC GLM}
\begin{verbatim}
DATA tomato;
  INFILE 'Ch13-tomato.csv' DSD FIRSTOBS=2;
  INPUT variety $ density yield;

PROC GLM DATA=tomato PLOTS=all;
  CLASS variety density;
  MODEL yield = variety|density / SOLUTION;
  LSMEANS variety / cl adjust=tukey;
  LSMEANS density / cl adjust=tukey;
  LSMEANS variety*density / cl adjust=tukey;
  RUN;
\end{verbatim}
}

\frame[containsverbatim]{\frametitle{Two-way ANOVA using PROC GLM}
{\tiny
\begin{verbatim}
                                        The GLM Procedure

Dependent Variable: yield

                                               Sum of
       Source                      DF         Squares     Mean Square    F Value    Pr > F
       Model                       11     422.3155556      38.3923232      24.22    <.0001
       Error                       24      38.0400000       1.5850000
       Corrected Total             35     460.3555556

                       R-Square     Coeff Var      Root MSE    yield Mean
                       0.917368      9.064568      1.258968      13.88889

       Source                      DF       Type I SS     Mean Square    F Value    Pr > F
       variety                      2     327.5972222     163.7986111     103.34    <.0001
       density                      3      86.6866667      28.8955556      18.23    <.0001
       variety*density              6       8.0316667       1.3386111       0.84    0.5484

       Source                      DF     Type III SS     Mean Square    F Value    Pr > F
       variety                      2     327.5972222     163.7986111     103.34    <.0001
       density                      3      86.6866667      28.8955556      18.23    <.0001
       variety*density              6       8.0316667       1.3386111       0.84    0.5484
\end{verbatim}
}

The Type I and Type III SS are equal because the design is balanced.
}

\frame[containsverbatim]{\frametitle{Two-way ANOVA using PROC GLM}
{\tiny
\begin{verbatim}
MODEL yield = variety|density / SOLUTION;
                                        The GLM Procedure

                                                        Standard
         Parameter                    Estimate             Error    t Value    Pr > |t|

         Intercept                 18.16666667 B      0.72686542      24.99      <.0001
         variety         A         -7.36666667 B      1.02794293      -7.17      <.0001
         variety         B         -5.40000000 B      1.02794293      -5.25      <.0001
         variety         C          0.00000000 B       .                .         .    
         density         10        -1.86666667 B      1.02794293      -1.82      0.0819
         density         20        -0.06666667 B      1.02794293      -0.06      0.9488
         density         30         1.76666667 B      1.02794293       1.72      0.0986
         density         40         0.00000000 B       .                .         .    
         variety*density A 10       0.26666667 B      1.45373083       0.18      0.8560
         variety*density A 20       1.70000000 B      1.45373083       1.17      0.2537
         variety*density A 30       0.33333333 B      1.45373083       0.23      0.8206
         variety*density A 40       0.00000000 B       .                .         .    
         variety*density B 10      -1.96666667 B      1.45373083      -1.35      0.1887
         variety*density B 20      -0.06666667 B      1.45373083      -0.05      0.9638
         variety*density B 30      -0.03333333 B      1.45373083      -0.02      0.9819
         variety*density B 40       0.00000000 B       .                .         .    
         variety*density C 10       0.00000000 B       .                .         .    
\end{verbatim}
}
}

\begin{frame}[fragile]
<<>>=
sm = ddply(tomato, .(Density, Variety), summarize, mean=mean(Yield))
ggplot(sm, aes(x=Density, y=mean, col=Variety)) + geom_line() +labs(y="Mean Yield")
@
\end{frame}





\frame[containsverbatim]{\frametitle{Is the mean yield for variety A different from B \alert{on average}?}
{\tiny
\begin{verbatim}
LSMEANS variety / cl adjust=tukey;
                                       Least Squares Means
                           Adjustment for Multiple Comparisons: Tukey

...

                             Least Squares Means for effect variety
                              Pr > |t| for H0: LSMean(i)=LSMean(j)

                                   Dependent Variable: yield

                         i/j              1             2             3
                            1                      0.2249        <.0001
                            2        0.2249                      <.0001
                            3        <.0001        <.0001

                      variety    yield LSMEAN      95% Confidence Limits
                      A             11.333333       10.583245    12.083422
                      B             12.208333       11.458245    12.958422
                      C             18.125000       17.374912    18.875088

                              Least Squares Means for Effect variety
                                   Difference         Simultaneous 95%
                                      Between      Confidence Limits for
                       i    j           Means       LSMean(i)-LSMean(j)
                       1    2       -0.875000       -2.158534     0.408534
                       1    3       -6.791667       -8.075201    -5.508132
                       2    3       -5.916667       -7.200201    -4.633132
\end{verbatim}
}
}





\frame[containsverbatim]{\frametitle{Is the mean yield at density 10 different from density 20 \alert{on average}?}
{\tiny
\begin{verbatim}
LSMEANS density / cl adjust=tukey;
                                       Least Squares Means
                           Adjustment for Multiple Comparisons: Tukey
                                        ...

                      density    yield LSMEAN      95% Confidence Limits
                      10            11.477778       10.611650    12.343905
                      20            14.388889       13.522762    15.255016
                      30            15.777778       14.911650    16.643905
                      40            13.911111       13.044984    14.777238

                              Least Squares Means for Effect density
                                   Difference         Simultaneous 95%
                                      Between      Confidence Limits for
                       i    j           Means       LSMean(i)-LSMean(j)

                       1    2       -2.911111       -4.548299    -1.273923
                       1    3       -4.300000       -5.937188    -2.662812
                       1    4       -2.433333       -4.070521    -0.796145
                       2    3       -1.388889       -3.026077     0.248299
                       2    4        0.477778       -1.159410     2.114966
                       3    4        1.866667        0.229479     3.503855
\end{verbatim}
}
}



\frame[containsverbatim]{\frametitle{Is mean yield different for particular combinations?}
{\tiny
\begin{verbatim}
LSMEANS variety*density / cl adjust=tukey;

                 variety    density    yield LSMEAN      95% Confidence Limits

                 A          10             9.200000        7.699824    10.700176
                 A          20            12.433333       10.933157    13.933510
                 A          30            12.900000       11.399824    14.400176
                 A          40            10.800000        9.299824    12.300176
                 B          10             8.933333        7.433157    10.433510
                 B          20            12.633333       11.133157    14.133510
                 B          30            14.500000       12.999824    16.000176
                 B          40            12.766667       11.266490    14.266843
                 C          10            16.300000       14.799824    17.800176
                 C          20            18.100000       16.599824    19.600176
                 C          30            19.933333       18.433157    21.433510
                 C          40            18.166667       16.666490    19.666843
\end{verbatim}
}
}



\frame[containsverbatim]{\frametitle{Is mean yield different for particular combinations?}
{\tiny
\begin{verbatim}
LSMEANS variety*density / cl adjust=tukey;

                          Least Squares Means for Effect variety*density
 
                                    Difference         Simultaneous 95%
                                       Between      Confidence Limits for
                       i     j           Means       LSMean(i)-LSMean(j)
                       1     2       -3.233333       -6.939704     0.473037
                       1     3       -3.700000       -7.406371     0.006371
                       1     4       -1.600000       -5.306371     2.106371
                       1     5        0.266667       -3.439704     3.973037
                       1     6       -3.433333       -7.139704     0.273037
                       1     7       -5.300000       -9.006371    -1.593629
                       1     8       -3.566667       -7.273037     0.139704
                       1     9       -7.100000      -10.806371    -3.393629
                       1    10       -8.900000      -12.606371    -5.193629
                       1    11      -10.733333      -14.439704    -7.026963
                       1    12       -8.966667      -12.673037    -5.260296
                       2     3       -0.466667       -4.173037     3.239704
                       2     4        1.633333       -2.073037     5.339704
                       2     5        3.500000       -0.206371     7.206371
                       2     6       -0.200000       -3.906371     3.506371
                       2     7       -2.066667       -5.773037     1.639704
                       2     8       -0.333333       -4.039704     3.373037
                       2     9       -3.866667       -7.573037    -0.160296
                       2    10       -5.666667       -9.373037    -1.960296
                       2    11       -7.500000      -11.206371    -3.793629
                       2    12       -5.733333       -9.439704    -2.026963
                       3     4        2.100000       -1.606371     5.806371
                       3     5        3.966667        0.260296     7.673037
                       3     6        0.266667       -3.439704     3.973037
                       3     7       -1.600000       -5.306371     2.106371
                       3     8        0.133333       -3.573037     3.839704
                       3     9       -3.400000       -7.106371     0.306371
                       3    10       -5.200000       -8.906371    -1.493629
                       3    11       -7.033333      -10.739704    -3.326963
                       3    12       -5.266667       -8.973037    -1.560296
                       4     5        1.866667       -1.839704     5.573037
                       4     6       -1.833333       -5.539704     1.873037
                       4     7       -3.700000       -7.406371     0.006371
                       4     8       -1.966667       -5.673037     1.739704
                       4     9       -5.500000       -9.206371    -1.793629
                       4    10       -7.300000      -11.006371    -3.593629
                       4    11       -9.133333      -12.839704    -5.426963
                       4    12       -7.366667      -11.073037    -3.660296
                       5     6       -3.700000       -7.406371     0.006371
                       5     7       -5.566667       -9.273037    -1.860296
                       5     8       -3.833333       -7.539704    -0.126963
                       5     9       -7.366667      -11.073037    -3.660296
                       5    10       -9.166667      -12.873037    -5.460296
                       5    11      -11.000000      -14.706371    -7.293629
                       5    12       -9.233333      -12.939704    -5.526963
                       6     7       -1.866667       -5.573037     1.839704
                       6     8       -0.133333       -3.839704     3.573037
                       6     9       -3.666667       -7.373037     0.039704
                       6    10       -5.466667       -9.173037    -1.760296
                       6    11       -7.300000      -11.006371    -3.593629
                       6    12       -5.533333       -9.239704    -1.826963
                       7     8        1.733333       -1.973037     5.439704
                       7     9       -1.800000       -5.506371     1.906371
                       7    10       -3.600000       -7.306371     0.106371
                       7    11       -5.433333       -9.139704    -1.726963
                       7    12       -3.666667       -7.373037     0.039704
                       8     9       -3.533333       -7.239704     0.173037
                       8    10       -5.333333       -9.039704    -1.626963
                       8    11       -7.166667      -10.873037    -3.460296
                       8    12       -5.400000       -9.106371    -1.693629
                       9    10       -1.800000       -5.506371     1.906371
                       9    11       -3.633333       -7.339704     0.073037
                       9    12       -1.866667       -5.573037     1.839704
                      10    11       -1.833333       -5.539704     1.873037
                      10    12       -0.066667       -3.773037     3.639704
                      11    12        1.766667       -1.939704     5.473037
\end{verbatim}
}
}


\subsection{Analysis in R}
\begin{frame}[fragile]
\frametitle{}
<<echo=TRUE>>=
tomato$Density = factor(tomato$Density)
m = lm(Yield~Variety*Density, tomato)
anova(m)
@
\end{frame}

\begin{frame}[fragile]
\frametitle{}
<<echo=TRUE>>=
library(lsmeans)
lsmeans(m, pairwise~Variety)
@
\end{frame}

\begin{frame}[fragile]
\frametitle{}
<<echo=TRUE>>=
lsmeans(m, pairwise~Density)
@
\end{frame}


\begin{frame}[fragile]
\frametitle{}
<<echo=TRUE>>=
lsmeans(m, pairwise~Variety*Density)
@
\end{frame}


\subsection{Summary}
\frame{\frametitle{Summary}
	\begin{itemize}[<+->]
	\item Use LSMEANS to answer questions of scientific interest.
	\item Check model assumptions
	\item Consider alternative models, e.g. treating density as continuous 
	\end{itemize}
}



\section{Unbalanced design}
\begin{frame}
\frametitle{Unbalanced design}

Suppose for some reason that a variety B, density 30 sample was contaminated. \pause Although you started with a balanced design, the data is now unbalanced. \pause Fortunately, we can still use the tools we have used previously. 

\end{frame}


\begin{frame}[fragile]
<<>>=
tomato_unbalanced = tomato[-19,]
ggplot(tomato_unbalanced, aes(x=Density, y=Yield, color=Variety)) + geom_point()
@
\end{frame}



\begin{frame}[fragile]
\frametitle{Summary statistics}

Number of replicates
<<>>=
dcast(tomato_unbalanced, Variety~Density, value.var="Yield", fun=length)
@

Mean Yield 
<<>>=
dcast(tomato_unbalanced, Variety~Density, value.var="Yield", fun=mean)
@

Standard deviation of yield
<<>>=
dcast(tomato_unbalanced, Variety~Density, value.var="Yield", fun=sd)
@

\end{frame}



\subsection{Analysis in SAS}
\frame[containsverbatim]{\frametitle{Two-way ANOVA using PROC GLM}
{\tiny
\begin{verbatim}
DATA tomato;
  INFILE 'Ch13-tomato.csv' DSD FIRSTOBS=2;
  INPUT variety $ density yield;
  i = _n_;

PROC GLM DATA=tomato PLOTS=all;
  WHERE i ~= 19; /* not equal to 19 */
  CLASS variety density;
  MODEL yield = variety|density / SOLUTION;
  LSMEANS variety / cl adjust=tukey;
  LSMEANS density / cl adjust=tukey;
  LSMEANS variety*density / cl adjust=tukey;
  RUN;
\end{verbatim}
}
}


\frame[containsverbatim]{\frametitle{Two-way ANOVA using PROC GLM}
{\tiny
\begin{verbatim}
                                        The GLM Procedure
 
Dependent Variable: yield   

                                               Sum of
       Source                      DF         Squares     Mean Square    F Value    Pr > F
       Model                       11     423.2388571      38.4762597      23.87    <.0001
       Error                       23      37.0800000       1.6121739                     
       Corrected Total             34     460.3188571                                     

                       R-Square     Coeff Var      Root MSE    yield Mean
                       0.919447      9.138391      1.269714      13.89429

       Source                      DF       Type I SS     Mean Square    F Value    Pr > F
       variety                      2     329.9878723     164.9939361     102.34    <.0001
       density                      3      84.4486608      28.1495536      17.46    <.0001
       variety*density              6       8.8023241       1.4670540       0.91    0.5052

       Source                      DF     Type III SS     Mean Square    F Value    Pr > F
       variety                      2     320.0374679     160.0187340      99.26    <.0001
       density                      3      86.0657613      28.6885871      17.79    <.0001
       variety*density              6       8.8023241       1.4670540       0.91    0.5052
\end{verbatim}
}
}


\frame[containsverbatim]{\frametitle{Two-way ANOVA using PROC GLM}
{\tiny
\begin{verbatim}
                                                        Standard
         Parameter                    Estimate             Error    t Value    Pr > |t|

         Intercept                 18.16666667 B      0.73306978      24.78      <.0001
         variety         A         -7.36666667 B      1.03671723      -7.11      <.0001
         variety         B         -5.40000000 B      1.03671723      -5.21      <.0001
         variety         C          0.00000000 B       .                .         .    
         density         10        -1.86666667 B      1.03671723      -1.80      0.0849
         density         20        -0.06666667 B      1.03671723      -0.06      0.9493
         density         30         1.76666667 B      1.03671723       1.70      0.1018
         density         40         0.00000000 B       .                .         .    
         variety*density A 10       0.26666667 B      1.46613956       0.18      0.8573
         variety*density A 20       1.70000000 B      1.46613956       1.16      0.2581
         variety*density A 30       0.33333333 B      1.46613956       0.23      0.8222
         variety*density A 40       0.00000000 B       .                .         .    
         variety*density B 10      -1.96666667 B      1.46613956      -1.34      0.1929
         variety*density B 20      -0.06666667 B      1.46613956      -0.05      0.9641
         variety*density B 30       0.36666667 B      1.55507584       0.24      0.8157
         variety*density B 40       0.00000000 B       .                .         .    
         variety*density C 10       0.00000000 B       .                .         .    
         variety*density C 20       0.00000000 B       .                .         .    
         variety*density C 30       0.00000000 B       .                .         .    
         variety*density C 40       0.00000000 B       .                .         .    
\end{verbatim}
}
}


\frame[containsverbatim]{\frametitle{Two-way ANOVA using PROC GLM}
{\tiny
\begin{verbatim}
                                        The GLM Procedure
                                       Least Squares Means
                        Adjustment for Multiple Comparisons: Tukey-Kramer

                             Least Squares Means for effect variety
                              Pr > |t| for H0: LSMean(i)=LSMean(j)
                                                
                                   Dependent Variable: yield
 
                         i/j              1             2             3
                            1                      0.1839        <.0001
                            2        0.1839                      <.0001
                            3        <.0001        <.0001              

                      variety    yield LSMEAN      95% Confidence Limits
                      A             11.333333       10.575098    12.091569
                      B             12.308333       11.504103    13.112563
                      C             18.125000       17.366765    18.883235

                              Least Squares Means for Effect variety
 
                                   Difference         Simultaneous 95%
                                      Between      Confidence Limits for
                       i    j           Means       LSMean(i)-LSMean(j)
                       1    2       -0.975000       -2.313097     0.363097
                       1    3       -6.791667       -8.089811    -5.493522
                       2    3       -5.816667       -7.154763    -4.478570
\end{verbatim}
}
}


\frame[containsverbatim]{\frametitle{Two-way ANOVA using PROC GLM}
{\tiny
\begin{verbatim}
                                        The GLM Procedure
                                       Least Squares Means
                        Adjustment for Multiple Comparisons: Tukey-Kramer

                             Least Squares Means for effect density
                              Pr > |t| for H0: LSMean(i)=LSMean(j)
                                                
                                   Dependent Variable: yield
 
                  i/j              1             2             3             4
                     1                      0.0004        <.0001        0.0025
                     2        0.0004                      0.0967        0.8545
                     3        <.0001        0.0967                      0.0189
                     4        0.0025        0.8545        0.0189              

                      density    yield LSMEAN      95% Confidence Limits

                      10            11.477778       10.602243    12.353312
                      20            14.388889       13.513354    15.264423
                      30            15.911111       14.965426    16.856797
                      40            13.911111       13.035577    14.786646

                              Least Squares Means for Effect density
 
                                   Difference         Simultaneous 95%
                                      Between      Confidence Limits for
                       i    j           Means       LSMean(i)-LSMean(j)
                       1    2       -2.911111       -4.567433    -1.254789
                       1    3       -4.433333       -6.157288    -2.709379
                       1    4       -2.433333       -4.089656    -0.777011
                       2    3       -1.522222       -3.246177     0.201733
                       2    4        0.477778       -1.178544     2.134100
                       3    4        2.000000        0.276045     3.723955
\end{verbatim}
}
}


\frame[containsverbatim]{\frametitle{Two-way ANOVA using PROC GLM}
{\tiny
\begin{verbatim}
                                        The GLM Procedure
                                       Least Squares Means
                        Adjustment for Multiple Comparisons: Tukey-Kramer

                                                                 LSMEAN
                         variety    density    yield LSMEAN      Number
                         A          10            9.2000000           1
                         A          20           12.4333333           2
                         A          30           12.9000000           3
                         A          40           10.8000000           4
                         B          10            8.9333333           5
                         B          20           12.6333333           6
                         B          30           14.9000000           7
                         B          40           12.7666667           8
                         C          10           16.3000000           9
                         C          20           18.1000000          10
                         C          30           19.9333333          11
                         C          40           18.1666667          12
\end{verbatim}
}
}



\frame[containsverbatim]{\frametitle{Two-way ANOVA using PROC GLM}
{\tiny
\begin{verbatim}
                                        The GLM Procedure
                                       Least Squares Means
                        Adjustment for Multiple Comparisons: Tukey-Kramer

                          Least Squares Means for Effect variety*density
 
                                    Difference         Simultaneous 95%
                                       Between      Confidence Limits for
                       i     j           Means       LSMean(i)-LSMean(j)
                       1    11      -10.733333      -14.487164    -6.979502
                       1    12       -8.966667      -12.720498    -5.212836
                       2     3       -0.466667       -4.220498     3.287164
                       2     4        1.633333       -2.120498     5.387164
                       2     5        3.500000       -0.253831     7.253831
                       2     6       -0.200000       -3.953831     3.553831
                       2     7       -2.466667       -6.663577     1.730244
                       2     8       -0.333333       -4.087164     3.420498
                       2     9       -3.866667       -7.620498    -0.112836
                       2    10       -5.666667       -9.420498    -1.912836
                       2    11       -7.500000      -11.253831    -3.746169
                       2    12       -5.733333       -9.487164    -1.979502
                       3     4        2.100000       -1.653831     5.853831
                       3     5        3.966667        0.212836     7.720498
                       3     6        0.266667       -3.487164     4.020498
                       3     7       -2.000000       -6.196911     2.196911
                       3     8        0.133333       -3.620498     3.887164
                       3     9       -3.400000       -7.153831     0.353831
                       3    10       -5.200000       -8.953831    -1.446169
                       3    11       -7.033333      -10.787164    -3.279502
                       3    12       -5.266667       -9.020498    -1.512836
                       4     5        1.866667       -1.887164     5.620498
                       4     6       -1.833333       -5.587164     1.920498
                       4     7       -4.100000       -8.296911     0.096911
                       4     8       -1.966667       -5.720498     1.787164
                       4     9       -5.500000       -9.253831    -1.746169
                       4    10       -7.300000      -11.053831    -3.546169
                       4    11       -9.133333      -12.887164    -5.379502
                       4    12       -7.366667      -11.120498    -3.612836
                       5     6       -3.700000       -7.453831     0.053831
                       5     7       -5.966667      -10.163577    -1.769756
                       5     8       -3.833333       -7.587164    -0.079502
                       5     9       -7.366667      -11.120498    -3.612836
                       5    10       -9.166667      -12.920498    -5.412836
                       5    11      -11.000000      -14.753831    -7.246169
                       5    12       -9.233333      -12.987164    -5.479502
                       6     7       -2.266667       -6.463577     1.930244
                       6     8       -0.133333       -3.887164     3.620498
                       6     9       -3.666667       -7.420498     0.087164
                       6    10       -5.466667       -9.220498    -1.712836
                       6    11       -7.300000      -11.053831    -3.546169
                       6    12       -5.533333       -9.287164    -1.779502
                       7     8        2.133333       -2.063577     6.330244
                       7     9       -1.400000       -5.596911     2.796911
                       7    10       -3.200000       -7.396911     0.996911
                       7    11       -5.033333       -9.230244    -0.836423
                       7    12       -3.266667       -7.463577     0.930244
                       8     9       -3.533333       -7.287164     0.220498
                       8    10       -5.333333       -9.087164    -1.579502
                       8    11       -7.166667      -10.920498    -3.412836
                       8    12       -5.400000       -9.153831    -1.646169
                       9    10       -1.800000       -5.553831     1.953831
                       9    11       -3.633333       -7.387164     0.120498
                       9    12       -1.866667       -5.620498     1.887164
                      10    11       -1.833333       -5.587164     1.920498
                      10    12       -0.066667       -3.820498     3.687164
                      11    12        1.766667       -1.987164     5.520498
\end{verbatim}
}
}



\subsection{Analysis in R}
\begin{frame}[fragile]
\frametitle{}
<<echo=TRUE>>=
m = lm(Yield~Variety*Density, tomato)
anova(m)
@
\end{frame}

\begin{frame}[fragile]
\frametitle{}
<<echo=TRUE>>=
lsmeans(m, pairwise~Variety)
@
\end{frame}

\begin{frame}[fragile]
\frametitle{}
<<echo=TRUE>>=
lsmeans(m, pairwise~Density)
@
\end{frame}


\begin{frame}[fragile]
\frametitle{}
<<echo=TRUE>>=
lsmeans(m, pairwise~Variety*Density)
@
\end{frame}

\subsection{Summary}
\begin{frame}
\frametitle{Summary}

The analysis can be completed just like the balanced design using LSMEANS to answer scientific questions of interest. 

\end{frame}



\section{Incomplete design}
\begin{frame}
\frametitle{Incomplete design}

Suppose none of the samples from Variety B, density 30 were obtained. \pause Now the analysis becomes more complicated. 

\end{frame}




\begin{frame}[fragile]
<<>>=
tomato_incomplete = tomato[-c(19:21),]
ggplot(tomato_incomplete, aes(x=Density, y=Yield, color=Variety)) + geom_point()
@
\end{frame}



\begin{frame}[fragile]
\frametitle{Summary statistics}

Number of replicates
<<>>=
dcast(tomato_incomplete, Variety~Density, value.var="Yield", fun=length)
@

Mean Yield 
<<>>=
dcast(tomato_incomplete, Variety~Density, value.var="Yield", fun=mean)
@

Standard deviation of yield
<<>>=
dcast(tomato_incomplete, Variety~Density, value.var="Yield", fun=sd)
@

\end{frame}



\subsection{Analysis in SAS}
\frame[containsverbatim]{\frametitle{Two-way ANOVA using PROC GLM}
{\tiny
\begin{verbatim}
DATA tomato;
  INFILE 'Ch13-tomato.csv' DSD FIRSTOBS=2;
  INPUT variety $ density yield;

PROC GLM DATA=tomato PLOTS=all;
  WHERE ~(variety='B' & density=30);
  CLASS variety density;
  MODEL yield = variety|density / SOLUTION;
  LSMEANS variety / cl adjust=tukey;
  LSMEANS density / cl adjust=tukey;
  LSMEANS variety*density / cl adjust=tukey;
  RUN;
\end{verbatim}
}
}


\frame[containsverbatim]{\frametitle{Two-way ANOVA using PROC GLM}
{\tiny
\begin{verbatim}
                                        The GLM Procedure
Dependent Variable: yield   
                                               Sum of
       Source                      DF         Squares     Mean Square    F Value    Pr > F
       Model                       10     421.0933333      42.1093333      25.33    <.0001
       Error                       22      36.5800000       1.6627273                     
       Corrected Total             32     457.6733333                                     

                       R-Square     Coeff Var      Root MSE    yield Mean
                       0.920074      9.321454      1.289468      13.83333

       Source                      DF       Type I SS     Mean Square    F Value    Pr > F
       variety                      2     347.3819444     173.6909722     104.46    <.0001
       density                      3      66.6531019      22.2177006      13.36    <.0001
       variety*density              5       7.0582870       1.4116574       0.85    0.5300

       Source                      DF     Type III SS     Mean Square    F Value    Pr > F
       variety                      2     321.2233796     160.6116898      96.60    <.0001
       density                      3      66.6531019      22.2177006      13.36    <.0001
       variety*density              5       7.0582870       1.4116574       0.85    0.5300
\end{verbatim}
}
}


\frame[containsverbatim]{\frametitle{Two-way ANOVA using PROC GLM}
{\tiny
\begin{verbatim}
                                                        Standard
         Parameter                    Estimate             Error    t Value    Pr > |t|
         Intercept                 18.16666667 B      0.74447460      24.40      <.0001
         variety         A         -7.36666667 B      1.05284607      -7.00      <.0001
         variety         B         -5.40000000 B      1.05284607      -5.13      <.0001
         variety         C          0.00000000 B       .                .         .    
         density         10        -1.86666667 B      1.05284607      -1.77      0.0901
         density         20        -0.06666667 B      1.05284607      -0.06      0.9501
         density         30         1.76666667 B      1.05284607       1.68      0.1075
         density         40         0.00000000 B       .                .         .    
         variety*density A 10       0.26666667 B      1.48894919       0.18      0.8595
         variety*density A 20       1.70000000 B      1.48894919       1.14      0.2658
         variety*density A 30       0.33333333 B      1.48894919       0.22      0.8249
         variety*density A 40       0.00000000 B       .                .         .    
         variety*density B 10      -1.96666667 B      1.48894919      -1.32      0.2001
         variety*density B 20      -0.06666667 B      1.48894919      -0.04      0.9647
         variety*density B 40       0.00000000 B       .                .         .    
         variety*density C 10       0.00000000 B       .                .         .    
         variety*density C 20       0.00000000 B       .                .         .    
         variety*density C 30       0.00000000 B       .                .         .    
         variety*density C 40       0.00000000 B       .                .         .    
\end{verbatim}
}
Notice the missing variety*density B 30 line. 
}


\frame[containsverbatim]{\frametitle{Two-way ANOVA using PROC GLM}
{\tiny
\begin{verbatim}
                                        The GLM Procedure
                                       Least Squares Means
                        Adjustment for Multiple Comparisons: Tukey-Kramer
                        
                                                            LSMEAN
                               variety    yield LSMEAN      Number
                               A            11.3333333           1
                               B               Non-est           2
                               C            18.1250000           3
                               
                             Least Squares Means for effect variety
                              Pr > |t| for H0: LSMean(i)=LSMean(j)
                                              

                      variety    yield LSMEAN      95% Confidence Limits
                      A             11.333333       10.561360    12.105306
                      B                     .               .            .
                      C             18.125000       17.353027    18.896973

                              Least Squares Means for Effect variety
 
                                   Difference         Simultaneous 95%
                                      Between      Confidence Limits for
                       i    j           Means       LSMean(i)-LSMean(j)
                       1    2               .               .            .
                       1    3       -6.791667       -7.883358    -5.699975
                       2    3               .               .            .
\end{verbatim}
}
}


\frame[containsverbatim]{\frametitle{Two-way ANOVA using PROC GLM}
{\tiny
\begin{verbatim}
                                        The GLM Procedure
                                       Least Squares Means
                        Adjustment for Multiple Comparisons: Tukey-Kramer

                                                            LSMEAN
                               density    yield LSMEAN      Number
                               10           11.4777778           1
                               20           14.3888889           2
                               30              Non-est           3
                               40           13.9111111           4

                      density    yield LSMEAN      95% Confidence Limits
                      10            11.477778       10.586380    12.369175
                      20            14.388889       13.497491    15.280286
                      30                    .               .            .
                      40            13.911111       13.019714    14.802509

                              Least Squares Means for Effect density
 
                                   Difference         Simultaneous 95%
                                      Between      Confidence Limits for
                       i    j           Means       LSMean(i)-LSMean(j)
                       1    2       -2.911111       -4.438096    -1.384126
                       1    3               .               .            .
                       1    4       -2.433333       -3.960319    -0.906348
                       2    3               .               .            .
                       2    4        0.477778       -1.049207     2.004763
                       3    4               .               .            .
\end{verbatim}
}
}


\frame[containsverbatim]{\frametitle{Two-way ANOVA using PROC GLM}
{\tiny
\begin{verbatim}
                                        The GLM Procedure
                                       Least Squares Means
                           Adjustment for Multiple Comparisons: Tukey

                                                                 LSMEAN
                         variety    density    yield LSMEAN      Number
                         A          10            9.2000000           1
                         A          20           12.4333333           2
                         A          30           12.9000000           3
                         A          40           10.8000000           4
                         B          10            8.9333333           5
                         B          20           12.6333333           6
                         B          40           12.7666667           7
                         C          10           16.3000000           8
                         C          20           18.1000000           9
                         C          30           19.9333333          10
\end{verbatim}
}
}



\frame[containsverbatim]{\frametitle{Two-way ANOVA using PROC GLM}
{\tiny
\begin{verbatim}
                                    Difference         Simultaneous 95%
                                       Between      Confidence Limits for
                       i     j           Means       LSMean(i)-LSMean(j)
                       1     2       -3.233333       -6.997053     0.530387
                       1     3       -3.700000       -7.463720     0.063720
                       1     4       -1.600000       -5.363720     2.163720
                       1     5        0.266667       -3.497053     4.030387
                       1     6       -3.433333       -7.197053     0.330387
                       1     7       -3.566667       -7.330387     0.197053
                       1     8       -7.100000      -10.863720    -3.336280
                       1     9       -8.900000      -12.663720    -5.136280
                       1    10      -10.733333      -14.497053    -6.969613
                       1    11       -8.966667      -12.730387    -5.202947
                       2     3       -0.466667       -4.230387     3.297053
                       2     4        1.633333       -2.130387     5.397053
                       2     5        3.500000       -0.263720     7.263720
                       2     6       -0.200000       -3.963720     3.563720
                       2     7       -0.333333       -4.097053     3.430387
                       2     8       -3.866667       -7.630387    -0.102947
                       2     9       -5.666667       -9.430387    -1.902947
                       2    10       -7.500000      -11.263720    -3.736280
                       2    11       -5.733333       -9.497053    -1.969613
                       3     4        2.100000       -1.663720     5.863720
                       3     5        3.966667        0.202947     7.730387
                       3     6        0.266667       -3.497053     4.030387
                       3     7        0.133333       -3.630387     3.897053
                       3     8       -3.400000       -7.163720     0.363720
                       3     9       -5.200000       -8.963720    -1.436280
                       3    10       -7.033333      -10.797053    -3.269613
                       3    11       -5.266667       -9.030387    -1.502947
                       4     5        1.866667       -1.897053     5.630387
                       4     6       -1.833333       -5.597053     1.930387
                       4     7       -1.966667       -5.730387     1.797053
                       4     8       -5.500000       -9.263720    -1.736280
                       4     9       -7.300000      -11.063720    -3.536280
                       4    10       -9.133333      -12.897053    -5.369613
                       4    11       -7.366667      -11.130387    -3.602947
                       5     6       -3.700000       -7.463720     0.063720
                       5     7       -3.833333       -7.597053    -0.069613
                       5     8       -7.366667      -11.130387    -3.602947
                       5     9       -9.166667      -12.930387    -5.402947
                       5    10      -11.000000      -14.763720    -7.236280
                       5    11       -9.233333      -12.997053    -5.469613
                       6     7       -0.133333       -3.897053     3.630387
                       6     8       -3.666667       -7.430387     0.097053
                       6     9       -5.466667       -9.230387    -1.702947
                       6    10       -7.300000      -11.063720    -3.536280
                       6    11       -5.533333       -9.297053    -1.769613
                       7     8       -3.533333       -7.297053     0.230387
                       7     9       -5.333333       -9.097053    -1.569613
                       7    10       -7.166667      -10.930387    -3.402947
                       7    11       -5.400000       -9.163720    -1.636280
                       8     9       -1.800000       -5.563720     1.963720
                       8    10       -3.633333       -7.397053     0.130387
                       8    11       -1.866667       -5.630387     1.897053
                       9    10       -1.833333       -5.597053     1.930387
                       9    11       -0.066667       -3.830387     3.697053
                      10    11        1.766667       -1.997053     5.530387
\end{verbatim}
}
}


\subsection{Treat as a One-way ANOVA}
\begin{frame}
\frametitle{Treat as a One-way ANOVA}

When the data are incomplete, use a one-way ANOVA combined with contrasts to answer questions of interest. \pause For example, to compare the average difference between B and C, we want to only compare at densities 10, 20, and 40. \pause 

  \[ \begin{array}{|c|c|c|c|c|}
	\hline
	& 10 & 20 & 30 & 40 \\
	\hline
	\mbox{A} & \mu_{11} & \mu_{12} & \mu_{13} & \mu_{14} \\
	\hline
	\mbox{B} & \mu_{21} & \mu_{22} & \mu_{23} & \mu_{24} \\
	\hline
	\mbox{C} & \mu_{31} & \mu_{32} & \mu_{33} & \mu_{34} \\
	\hline
	\end{array} \]
  
\pause 
Thus, the contrast is 

\[ \begin{array}{ll}
\gamma &= \frac{1}{3}(\mu_{31}+\mu_{32}+\mu_{34}) - \frac{1}{3}(\mu_{21}+\mu_{22}+\mu_{24}) \\
&= \frac{1}{3} (\mu_{31}+\mu_{32}+\mu_{34} - \mu_{21}-\mu_{22}-\mu_{24})
\end{array} \]

\end{frame}



\subsection{Analysis in SAS}
\frame[containsverbatim]{\frametitle{Two-way ANOVA using PROC GLM}
{\tiny
\begin{verbatim}
DATA tomato;
  INFILE 'Ch13-tomato.csv' DSD FIRSTOBS=2;
  INPUT variety $ density yield;

PROC GLM DATA=tomato PLOTS=all;
  WHERE ~(variety='B' & density=30);
  CLASS variety density;
  MODEL yield = variety*density / SOLUTION CLPARM;
  LSMEANS variety*density / cl adjust=tukey;
  /*                             A10 A20 A30 A40 B10 B20 B40 C10 C20 C30 C40 */
  ESTIMATE 'C-B' variety*density   0   0   0   0  -1  -1  -1   1   1   0   1 / DIVISOR=3;
  ESTIMATE 'C-A' variety*density  -1  -1  -1  -1   0   0   0   1   1   1   1 / DIVISOR=4;
  ESTIMATE 'B-A' variety*density  -1  -1   0  -1   1   1   1   0   0   0   0 / DIVISOR=3;
  /* we could do the densities similarly */
  RUN;
\end{verbatim}
}
}


\frame[containsverbatim]{\frametitle{Two-way ANOVA using PROC GLM}
{\tiny
\begin{verbatim}
                                        The GLM Procedure
Dependent Variable: yield   
                                               Sum of
       Source                      DF         Squares     Mean Square    F Value    Pr > F
       Model                       10     421.0933333      42.1093333      25.33    <.0001
       Error                       22      36.5800000       1.6627273                     
       Corrected Total             32     457.6733333                                     

                       R-Square     Coeff Var      Root MSE    yield Mean
                       0.920074      9.321454      1.289468      13.83333

       Source                      DF       Type I SS     Mean Square    F Value    Pr > F
       variety*density             10     421.0933333      42.1093333      25.33    <.0001

       Source                      DF     Type III SS     Mean Square    F Value    Pr > F
       variety*density             10     421.0933333      42.1093333      25.33    <.0001
\end{verbatim}
}
}


\frame[containsverbatim]{\frametitle{Two-way ANOVA using PROC GLM}
{\tiny
\begin{verbatim}
                                           Standard
Parameter                  Estimate           Error  t Value  Pr > |t|    95% Confidence Limits
Intercept               18.16666667 B    0.74447460    24.40    <.0001   16.62272085  19.71061248
variety*density A 10    -8.96666667 B    1.05284607    -8.52    <.0001  -11.15013578  -6.78319756
variety*density A 20    -5.73333333 B    1.05284607    -5.45    <.0001   -7.91680244  -3.54986422
variety*density A 30    -5.26666667 B    1.05284607    -5.00    <.0001   -7.45013578  -3.08319756
variety*density A 40    -7.36666667 B    1.05284607    -7.00    <.0001   -9.55013578  -5.18319756
variety*density B 10    -9.23333333 B    1.05284607    -8.77    <.0001  -11.41680244  -7.04986422
variety*density B 20    -5.53333333 B    1.05284607    -5.26    <.0001   -7.71680244  -3.34986422
variety*density B 40    -5.40000000 B    1.05284607    -5.13    <.0001   -7.58346911  -3.21653089
variety*density C 10    -1.86666667 B    1.05284607    -1.77    0.0901   -4.05013578   0.31680244
variety*density C 20    -0.06666667 B    1.05284607    -0.06    0.9501   -2.25013578   2.11680244
variety*density C 30     1.76666667 B    1.05284607     1.68    0.1075   -0.41680244   3.95013578
variety*density C 40     0.00000000 B     .              .       .         .            .        
\end{verbatim}
}
}


\begin{frame}
\frametitle{The Regression model}

The regression model here considers variety-density combination as a single explanatory variable with 11 levels: A10, A20, A30, A40, B10, B20, B40, C10, C20, C30, and C40. \pause By default, SAS chose C40 as our reference level. \pause For observation $i$, let

\begin{itemize}
\item $Y_i$ be the yield
\item $V_i$ be the variety
\item $D_i$ be the density
\end{itemize}

\pause 

The model is then $Y_i\stackrel{ind}{\sim} N(\mu_i, \sigma^2)$ and 
{\tiny
\[ \begin{array}{lllllll}
\mu_i &= \beta_0 
&+ \beta_1\I(V_i=A,D_i=10) &+ \beta_2\I(V_i=A,D_i=20)&+ \beta_3\I(V_i=A,D_i=30)&+ \beta_4\I(V_i=A,D_i=40) \\
&&+ \beta_5\I(V_i=B,D_i=10)&+ \beta_6\I(V_i=B,D_i=20)&&+ \beta_7\I(V_i=B,D_i=40) \\
&&+ \beta_8\I(V_i=C,D_i=10)&+ \beta_9\I(V_i=C,D_i=20)&+ \beta_{10}\I(V_i=C,D_i=30)
\end{array} \]
}
\end{frame}


\frame[containsverbatim]{\frametitle{Two-way ANOVA using PROC GLM}
{\tiny
\begin{verbatim}
                                        The GLM Procedure
 
Dependent Variable: yield   

                                         Standard
 Parameter                 Estimate         Error  t Value  Pr > |t|    95% Confidence Limits
 C-B                     6.07777778    0.60786096    10.00    <.0001    4.81715130   7.33840426
 C-A                     6.79166667    0.52642304    12.90    <.0001    5.69993211   7.88340122
 B-A                     0.63333333    0.60786096     1.04    0.3088   -0.62729315   1.89395981
\end{verbatim}
}
}

\frame[containsverbatim]{\frametitle{Two-way ANOVA using PROC GLM}
{\tiny
\begin{verbatim}
                                        The GLM Procedure
                                       Least Squares Means
                           Adjustment for Multiple Comparisons: Tukey

                                                                 LSMEAN
                         variety    density    yield LSMEAN      Number
                         A          10            9.2000000           1
                         A          20           12.4333333           2
                         A          30           12.9000000           3
                         A          40           10.8000000           4
                         B          10            8.9333333           5
                         B          20           12.6333333           6
                         B          40           12.7666667           7
                         C          10           16.3000000           8
                         C          20           18.1000000           9
                         C          30           19.9333333          10
\end{verbatim}
}
}







\frame[containsverbatim]{\frametitle{Two-way ANOVA using PROC GLM}
{\tiny
\begin{verbatim}
                                    Difference         Simultaneous 95%
                                       Between      Confidence Limits for
                       i     j           Means       LSMean(i)-LSMean(j)
                       1     2       -3.233333       -6.997053     0.530387
                       1     3       -3.700000       -7.463720     0.063720
                       1     4       -1.600000       -5.363720     2.163720
                       1     5        0.266667       -3.497053     4.030387
                       1     6       -3.433333       -7.197053     0.330387
                       1     7       -3.566667       -7.330387     0.197053
                       1     8       -7.100000      -10.863720    -3.336280
                       1     9       -8.900000      -12.663720    -5.136280
                       1    10      -10.733333      -14.497053    -6.969613
                       1    11       -8.966667      -12.730387    -5.202947
                       2     3       -0.466667       -4.230387     3.297053
                       2     4        1.633333       -2.130387     5.397053
                       2     5        3.500000       -0.263720     7.263720
                       2     6       -0.200000       -3.963720     3.563720
                       2     7       -0.333333       -4.097053     3.430387
                       2     8       -3.866667       -7.630387    -0.102947
                       2     9       -5.666667       -9.430387    -1.902947
                       2    10       -7.500000      -11.263720    -3.736280
                       2    11       -5.733333       -9.497053    -1.969613
                       3     4        2.100000       -1.663720     5.863720
                       3     5        3.966667        0.202947     7.730387
                       3     6        0.266667       -3.497053     4.030387
                       3     7        0.133333       -3.630387     3.897053
                       3     8       -3.400000       -7.163720     0.363720
                       3     9       -5.200000       -8.963720    -1.436280
                       3    10       -7.033333      -10.797053    -3.269613
                       3    11       -5.266667       -9.030387    -1.502947
                       4     5        1.866667       -1.897053     5.630387
                       4     6       -1.833333       -5.597053     1.930387
                       4     7       -1.966667       -5.730387     1.797053
                       4     8       -5.500000       -9.263720    -1.736280
                       4     9       -7.300000      -11.063720    -3.536280
                       4    10       -9.133333      -12.897053    -5.369613
                       4    11       -7.366667      -11.130387    -3.602947
                       5     6       -3.700000       -7.463720     0.063720
                       5     7       -3.833333       -7.597053    -0.069613
                       5     8       -7.366667      -11.130387    -3.602947
                       5     9       -9.166667      -12.930387    -5.402947
                       5    10      -11.000000      -14.763720    -7.236280
                       5    11       -9.233333      -12.997053    -5.469613
                       6     7       -0.133333       -3.897053     3.630387
                       6     8       -3.666667       -7.430387     0.097053
                       6     9       -5.466667       -9.230387    -1.702947
                       6    10       -7.300000      -11.063720    -3.536280
                       6    11       -5.533333       -9.297053    -1.769613
                       7     8       -3.533333       -7.297053     0.230387
                       7     9       -5.333333       -9.097053    -1.569613
                       7    10       -7.166667      -10.930387    -3.402947
                       7    11       -5.400000       -9.163720    -1.636280
                       8     9       -1.800000       -5.563720     1.963720
                       8    10       -3.633333       -7.397053     0.130387
                       8    11       -1.866667       -5.630387     1.897053
                       9    10       -1.833333       -5.597053     1.930387
                       9    11       -0.066667       -3.830387     3.697053
                      10    11        1.766667       -1.997053     5.530387
\end{verbatim}
}
}




\subsection{Analysis in R}
\begin{frame}[fragile]
\frametitle{}
<<echo=TRUE>>=
m = lm(Yield~Variety:Density, tomato, subset=!(Variety=='B' & Density==30))
anova(m)
@
\end{frame}

\begin{frame}[fragile]
\frametitle{}
<<echo=TRUE>>=
tomato$VarietyDensity = factor(paste(tomato$Variety, tomato$Density, sep=""))
# Note the -1 in order to construct the contrast
m = lm(Yield~VarietyDensity-1, tomato, subset=!(Variety=='B' & Density==30))
#                   A10 A20 A30 A40 B10 B20 B40 C10 C20 C30 C40   
K = rbind('C-B' = c(  0,  0,  0,  0, -1, -1, -1,  1,  1,  0,  1)/3,
          'C-A' = c( -1, -1, -1, -1,  0,  0,  0,  1,  1,  1,  1)/4,
          'B-A' = c( -1, -1,  0, -1,  1,  1,  1,  0,  0,  0,  0)/3)

library(multcomp)
t = glht(m, linfct=K)
#summary(t)
confint(t, calpha=univariate_calpha())
@
\end{frame}


\begin{frame}[fragile]
\frametitle{}
<<echo=TRUE>>=
m = lm(Yield~Variety:Density, tomato, subset=!(Variety=='B' & Density==30))
lsmeans(m, pairwise~Variety:Density)
# We could have used the VarietyDensity model, but this looks nicer
@
\end{frame}



\subsection{Summary}
\begin{frame}
\frametitle{Summary}

When dealing with an incomplete design, it is often easier to treat the analysis as a one-way ANOVA and use contrasts to answer scientific questions of interest.

\end{frame}




\section{Optimal yield}
\begin{frame}
\frametitle{Optimal yield}

Now suppose you have the same data set, but your scientific question is different. \pause Specifically, you are interested in choosing a variety and density that provide the optimal yield. 

\vspace{0.2in} \pause

You can use the ANOVA analysis to choose from amongst the 3 varieties and one of the 4 densities\pause, but there is no reason to believe that the optimal density will be one of those 4. 

\end{frame}


\begin{frame}[fragile]
<<>>=
tomato = read.csv("Ch13-tomato.csv")
tomato$Variety = relevel(tomato$Variety, ref="C")
ggplot(tomato, aes(x=Density, y=Yield, color=Variety)) + geom_point()
@
\end{frame}


\subsection{Modeling}
\begin{frame}
\frametitle{Modeling}

Considering a single variety, if we assume a linear relationship between Yield ($Y_i$) and Density ($D_i$) then the maximum Yield will occur at either $-\infty$ or $+\infty$ which is unreasonable. \pause The easiest way to have a maximum (or minimum) is to assume a quadratic relationship, e.g. 

\[ E[Y_i] = \mu_i = \beta_0 + \beta_1 D_i + \beta_2 D_i^2 \]

\pause
Now we can incorporate Variety ($V_i$) in many ways. \pause Two options are parallel curves or completely independent curves.

\vspace{0.2in} \pause

Parallel curves:

\[ \begin{array}{rl}
\mu_i =&  \beta_0 + \beta_1 D_i + \beta_2 D_i^2 \\
&+ \beta_3 \I(V_i=A) + \beta_4 \I(V_i=B) 
\end{array} \]

Independent lines:

\[ \begin{array}{rl}
\mu_i =&  \beta_0 + \beta_1 D_i + \beta_2 D_i^2 \\
&+ \beta_3 \I(V_i=A) D_i + \beta_4 \I(V_i=B) D_i  \\
&+ \beta_5 \I(V_i=A) D_i^2 + \beta_6 \I(V_i=B) D_i^2 
\end{array} \]

\end{frame}


\begin{frame}[fragile]
<<>>=
g1 = ggplot(tomato, aes(x=Density, y=Yield)) + geom_point() + 
  stat_smooth(method="lm", formula=y~x+I(x^2), se=FALSE, color="black") +
  labs(title="No variety")


# Need to construct the parallel curves 
lines = with(tomato,expand.grid(Density=seq(min(Density),max(Density),length=41),
                               Variety=levels(Variety)))
lines$Yield <- predict(lm(Yield~Density+I(Density^2)+Variety, tomato),lines)

g2 = ggplot(tomato, aes(x=Density, y=Yield, color=Variety)) + geom_point() + 
  geom_line(data=lines) +
  labs(title="Parallel curves")

g3 = ggplot(tomato, aes(x=Density, y=Yield, color=Variety)) + geom_point() + 
  stat_smooth(method="lm", formula=y~x+I(x^2), se=FALSE) +
  labs(title="Independent curves")
grid.arrange(g1,g2,g3, ncol=3)
@
\end{frame}



\begin{frame}
\frametitle{Finding the maximum}

For a particular variety, there will be an equation like 

\[ E[Y_i] = \mu_i = \beta_0 + \beta_1 D_i + \beta_2 D_i^2 \]

where these $\beta_1$ and $\beta_2$ need not correspond to any particular $\beta_1$ and $\beta_2$ we have discussed thus far. 

\vspace{0.2in} \pause

If $\beta_2<0$, then the quadratic curve has a maximum and it occurs at $-\beta_1/2\beta_2$. 

\end{frame}


\subsection{Analysis in SAS}
\frame[containsverbatim]{\frametitle{Analysis in SAS}
{\tiny
\begin{verbatim}
DATA tomato;
  INFILE 'Ch13-tomato.csv' DSD FIRSTOBS=2;
  INPUT variety $ density yield;

/* No variety */
PROC GLM DATA=tomato PLOTS=all;
  CLASS variety; /* density is no longer here */
  MODEL yield = density|density / SOLUTION;
  RUN;

/* Parallel curves */
PROC GLM DATA=tomato PLOTS=all;
  CLASS variety; /* density is no longer here */
  MODEL yield = density|density variety/ SOLUTION;
  RUN;

/* Independent curves */
PROC GLM DATA=tomato PLOTS=all;
  CLASS variety; /* density is no longer here */
  MODEL yield = density|density|variety/ SOLUTION;
  RUN;
\end{verbatim}
}
}


\frame[containsverbatim]{\frametitle{No variety}
{\tiny
\begin{verbatim}
                                        The GLM Procedure
 
Dependent Variable: yield   

                                               Sum of
       Source                      DF         Squares     Mean Square    F Value    Pr > F
       Model                        2      85.3346667      42.6673333       3.75    0.0340
       Error                       33     375.0208889      11.3642694                     
       Corrected Total             35     460.3555556                                     


...

       Source                      DF     Type III SS     Mean Square    F Value    Pr > F
       density                      1     65.30344358     65.30344358       5.75    0.0223
       density*density              1     51.36111111     51.36111111       4.52    0.0411

                                                     Standard
             Parameter               Estimate           Error    t Value    Pr > |t|
             Intercept            5.744444444      3.12824210       1.84      0.0753
             density              0.684111111      0.28538383       2.40      0.0223
             density*density     -0.011944444      0.00561849      -2.13      0.0411
\end{verbatim}
}
}

\frame[containsverbatim]{\frametitle{Parallel curves}
{\tiny
\begin{verbatim}
                                        The GLM Procedure
 
Dependent Variable: yield   

                                               Sum of
       Source                      DF         Squares     Mean Square    F Value    Pr > F
       Model                        4     412.9318889     103.2329722      67.48    <.0001
       Error                       31      47.4236667       1.5297957                     
       Corrected Total             35     460.3555556                                     

...

       Source                      DF     Type III SS     Mean Square    F Value    Pr > F
       density                      1      65.3034436      65.3034436      42.69    <.0001
       density*density              1      51.3611111      51.3611111      33.57    <.0001
       variety                      2     327.5972222     163.7986111     107.07    <.0001

                                                       Standard
           Parameter                 Estimate             Error    t Value    Pr > |t|
           Intercept              9.980555556 B      1.18419286       8.43      <.0001
           density                0.684111111        0.10470690       6.53      <.0001
           density*density       -0.011944444        0.00206142      -5.79      <.0001
           variety         A     -6.791666667 B      0.50494153     -13.45      <.0001
           variety         B     -5.916666667 B      0.50494153     -11.72      <.0001
           variety         C      0.000000000 B       .                .         .    
\end{verbatim}
}
}

\frame[containsverbatim]{\frametitle{Independent curves}
{\tiny
\begin{verbatim}
                                               Sum of
       Source                      DF         Squares     Mean Square    F Value    Pr > F
       Model                        8     419.8612222      52.4826528      34.99    <.0001
       Error                       27      40.4943333       1.4997901                     
       Corrected Total             35     460.3555556                                     
...

       Source                      DF     Type III SS     Mean Square    F Value    Pr > F
       density                      1     65.30344358     65.30344358      43.54    <.0001
       density*density              1     51.36111111     51.36111111      34.25    <.0001
       variety                      2     21.66539427     10.83269713       7.22    0.0031
       density*variety              2      2.07850215      1.03925108       0.69    0.5088
       densit*densit*variet         2      1.65388889      0.82694444       0.55    0.5825

                                                         Standard
        Parameter                      Estimate             Error    t Value    Pr > |t|
        Intercept                   11.80833333 B      1.96836425       6.00      <.0001
        density                      0.52016667 B      0.17957029       2.90      0.0074
        density*density             -0.00891667 B      0.00353529      -2.52      0.0179
        variety              A      -8.45833333 B      2.78368742      -3.04      0.0052
        variety              B      -9.73333333 B      2.78368742      -3.50      0.0016
        variety              C       0.00000000 B       .                .         .    
        density*variety      A       0.19916667 B      0.25395073       0.78      0.4397
        density*variety      B       0.29266667 B      0.25395073       1.15      0.2592
        density*variety      C       0.00000000 B       .                .         .    
        densit*densit*variet A      -0.00441667 B      0.00499965      -0.88      0.3848
        densit*densit*variet B      -0.00466667 B      0.00499965      -0.93      0.3589
        densit*densit*variet C       0.00000000 B       .                .         .    
\end{verbatim}
}
}


\subsection{Analysis in R}
\begin{frame}[fragile]
\frametitle{No variety}
<<>>=
summary(lm(Yield~Density+I(Density^2), tomato))
@
\end{frame}

\begin{frame}[fragile]
\frametitle{Parallel curves}
<<>>=
summary(lm(Yield~Density+I(Density^2) + Variety, tomato))
@
\end{frame}

\begin{frame}[fragile]
\frametitle{Independent curves}
<<>>=
summary(lm(Yield~Density*Variety+I(Density^2)*Variety, tomato))
@
\end{frame}



\section{Randomized complete block design}
\begin{frame}
\frametitle{Completely randomized design}

This semester, we have assumed a completely randomized design. \pause As an example, consider 36 plots and we are randomly assigning our variety-density combinations to the plots such that we have 3 reps of each combination. \pause The result may look something like this

<<>>=
set.seed(20121204)
opar = par(mar=rep(0,4))
plot(0,0, type="n", axes=F, 
     xlab='', ylab='', xlim=c(0.5,6.5), ylim=c(0.5,6.5))
abline(h=(1:7)-.5)
abline(v=(1:7)-.5)
trts = rep(paste(rep(c("A","B","C"),each=4), rep(seq(10,40,by=10), 3), sep=""),3)
text(rep(1:6, each=6), rep(1:6, 6), trts)
par(opar)
@

\end{frame}




\end{document}
