\documentclass[handout]{beamer}

\input{../frontmatter}
\input{../commands}

\title{Data}

\begin{document}

\begin{frame}
\titlepage
\end{frame}


\section{Data}
\begin{frame}
\frametitle{Data (Ch. 2)}
\framesubtitle{Variation}
\begin{definition}
\alert{Variation} refers to differences in a characteristic among individuals or 
items; 
variation can also refer to fluctuation over time. 
Variation is at the heart of statistics.
\end{definition}

\vspace{0.25cm} \pause

Examples:
\begin{itemize}[<+->]
\item stock values vary on a daily basis
\item sales for a company/store vary on a daily basis
\item commodities vary
\item customers' preferences for certain product features vary
\item \vdots
\end{itemize}
\end{frame}





\begin{frame}\frametitle{Data}
\framesubtitle{Variation}
Some first observations about variation:
\begin{itemize}
\item Variation is everywhere.
\item Individuals vary on many physical characteristics. 
\item Repeated measurements on an individual's characteristic are variable. 
\item Variability can have different causes.
\item Both qualitative and quantitative variables reveal variability in data.
\item Some things vary just a little, some vary a lot.
\end{itemize}

\vspace{0.25cm} \pause

Variability is what makes decisions in the face of uncertainty so difficult. Variability is what makes statistics so interesting and allows us to interpret, model and make predictions from data (Gould, 2004).

\vspace{0.25cm} \pause
 
The concept of variability will accompany us throughout all of the semester.
\end{frame}




\subsection{Variables}
\begin{frame}
\frametitle{Variables}

\begin{definition}
\alert{Individuals} are subjects/objects of the population of interest; can
be people but also business firms, common stocks or any other object
that we want to study.
\end{definition}

\pause

\begin{definition}
A \alert{variable} is any characteristic of an individual that we are
interested in.
\pause
A variable typically will take on different values for different individuals.
\pause
There are two types of variables:  \textbf{categorical}
(qualitative) and \textbf{quantitative}.
\end{definition}

\pause

\begin{definition}
An \alert{observation} in a data set refers to the observed value of a
variable on a specific individual.
\end{definition}
\end{frame}




\subsection{Random variables}
\begin{frame}
\frametitle{Random variables}

\begin{definition}
A \alert{random variable} is the as yet unknown outcome of some observation.
\pause
We typically denote random variables with capital Roman letters at the end of 
the alphabeta, e.g. $X$, $Y$, or $Z$.
\end{definition}

\vspace{0.1cm} \pause

Once we ``see'' an observation,
i.e. the outcome of $X, Y$ and $Z$ is determined and no longer unknown,
we switch to a lower case notation $x$, $y$ or $z$.

\vspace{0.1cm} \pause

Examples
\begin{itemize}[<+->]
\item $X$ = monthly unemployment rate
\item $Y$ = grade on your next Stat 226 exam, and
\item $Z$ = education of customer.
\end{itemize}
are all examples of random variables.
\end{frame}





\begin{frame}
\frametitle{Observations}

For example, the corresponding \alert{observations} could be:
\begin{itemize}
\item $x$= 3.9\% (for July 2018),
\item $y$= 95 points, and
\item $z$=College graduate
\end{itemize}

\vspace{1cm} \pause

\alert{TL;DR} 
Know the difference between a random variable and an observation (data point)
\pause
and how to distinguish between them in terms of notation!
\begin{itemize}
\item upper case letter $\implies$ not yet observed
\item lower case letter $\implies$ observed
\end{itemize}
\end{frame}








\subsection{Categorical variables}
\begin{frame}
\frametitle{Categorical Variables}

\begin{definition}{Categorical Variables}
A \alert{categorical variable} is a variable that can take on one of a limited, 
and usually fixed number of possible values, 
assigning each individual to a particular group based on some qualitative property.
\pause
A \alert{ordinal variable} is a categorical variable for which the values can
be ordered.
\pause
A \alert{nominal variable} is a categorical variable that has no ordering.
\end{definition}

\pause

\begin{itemize}[<+->]
\item Nominal: order not meaningful
  \begin{itemize}
  \item gender, religion, race
  \item type of stock
  \item pattern of a carpet
  \end{itemize}
\item Ordinal: order may be meaningful
  \begin{itemize}
  \item grades: A, A-, B+, B, B-, \ldots
  \item educational degrees
  \item Likert scales: disagree, neutral, agree
  \end{itemize}
\end{itemize}
\end{frame}






\begin{frame}
\frametitle{Numeric variables}

\begin{definition}
A \alert{numeric (or quantitative) variable} 
take numerical values 
\pause
for which arithmetic
operations such as adding and averaging make sense.
\end{definition}

\vspace{0.1in} \pause

Examples:
\begin{itemize}
\item height of a person
\item weight of a person
\item temperature
\item time it takes to run a mile
\item currency exchange rates
\item number of webpage hits in an hour
\end{itemize}
\end{frame}



\begin{frame}\frametitle{Data}
\framesubtitle{Descriptive Statistics versus Inferential Statistics}

\begin{definition}
\alert{Descriptive statistics} is the collection,
presentation and description of data in form of \textbf{graphs},
\textbf{tables},
and \textbf{numerical summaries} that provide meaningful information about the data.
\end{definition}

\vspace{0.1in}

Goals:
\begin{itemize}
\item look for patterns
\item summarize and present data
\end{itemize}

\vspace{0.1in}

Descriptive statistics focuses on obtaining a better understanding about the 
\textbf{distribution}\footnote{We will learn about the term distribution later.}, 
\textbf{variability}, and \textbf{central tendency} that a variable of interest exhibits.

\end{frame}


\subsection{Inferential statistics}
\begin{frame}
\frametitle{Inferential Statistics}
\framesubtitle{Descriptive Statistics versus Inferential Statistics}

\begin{definition}
\alert{Inferential statistics} deals with drawing conclusions and making
generalizations based on data for a larger group of subjects (a population).
\end{definition}

\vspace{0.1in} \pause

Goals:
\begin{itemize}
\item making statements about the population
\item making data-based decisions
\end{itemize}
\end{frame}




\subsection{Example}
\begin{frame}
\frametitle{Example: movie focus group}

Assume a selected sample of people is asked to provide an
overall rating for a movie resulting in the following:
\begin{itemize}
\item 24\% very satisfied, \quad  26\% satisfied, \quad 33\% in between
\item[] 12\% dissatisfied, and \quad  5\% very dissatisfied
\end{itemize}
\vspace{.25cm} 

$\Rightarrow$ 24\% of the \textbf{actual previewers}
were very satisfied with
the movie -- this is a \alert{descriptive statement} 
\pause 
because it is a statement about the people who actually viewed the movie.

$\Rightarrow$ We expect about 24\% of \alert{all people} going to see the movie will be very satisfied.  
-- This is an \alert{inferential statement} because it is about the population of 
all people who will see the movie (not just those we have data on).
\end{frame}




\section{Population}
\begin{frame}
\frametitle{Population}
\begin{definition}
The \alert{population} is the entire group of
individuals that we want to say something about.
\end{definition}

\vspace{0.1in} \pause

Examples:
\begin{itemize}
\item all currently enrolled ISU students 
\item all Starbucks customers nationwide 
\item all customers banking with Wells Fargo
\end{itemize}

\vspace{0.1in} \pause

The population is entirely defined by the target group of interest and the 
purpose of the study. 
\end{frame}







% 
% \begin{frame}\frametitle{Data} 
% \framesubtitle{Population and Processes \footnotesize{(we will revisit in Chapter 13.2)}}
% \begin{definition}{Process}
% A process is a component of a system (broadly defined) that has inputs and outputs.
% Many business applications involve processes, rather than populations.[.25cm]
% \textbf{Examples:}
% \begin{itemize}
% \item  Monthly sales in the NE region of the country
% \item Monthly unemployment rate in Iowa
% \item Yearly total yield of corn in Iowa
% \item End-of-month inventory level 
% \item The daily temperature in Ames, Iowa
% \end{itemize}
% \end{definition}
% \end{frame}
% 
% 
% \begin{frame}\frametitle{Data} 
% \framesubtitle{Samples \footnotesize{(we will revisit in Chapter 13.2)}}\vspace{-.5cm}
% \begin{definition}{Sample}
% A sample is a \textbf{part} \textbf{of a population} (usually chosen randomly)
% from which we obtain information in order to draw conclusions about
% the entire
% population (or process). [.25cm]
% \textbf{Examples:} \begin{itemize}
% \item From an alphabetical list every currently enrolled 5th ISU student.
% \item Starbucks customers at the Starbucks on Lincoln Way on August 22nd
% \item 100 randomly chosen customers banking with Wells Fargo
% \end{itemize}
% \end{definition}
% 
% \textbf{Caution:}
% The terms population and sample are \underline{relative} as they depend on the purpose of a study. 
%  [.5cm]
% 
% \red{ $\Rightarrow$ \textsc{Clearly formulate what is the population of interest!}}
% 
% \end{frame}
% 
% 
% \begin{frame}\frametitle{Data} 
% \framesubtitle{Summary Statistics  versus Parameters} 
% 
% 
% When using \textbf{numerical summaries} to describe samples or
% populations we need to distinguish between a so-called
% \textbf{summary statistic} and a \textbf{parameter}:
% \begin{itemize}
% \item any numerical summary describing a sample is called a
% \textbf{sample statistic}
% {\footnotesize{Note that the book's terminology is ``summary statistic'' which is rather uncommon.}}[.25cm]
% \item any numerical summary describing a population is called a
% \textbf{population parameter}
% \end{itemize}
% \vspace{.25cm} \textbf{Example:} Summer salary of ISU students
% \begin{itemize}
% \item Mean summer salary of all ISU students: \underline{population parameter} [.25cm]
% \item Mean summer salary of a random sample of 100 ISU students: \underline{sample statistic}
% \end{itemize}
% \end{frame}
% 
% 
% \begin{frame}\frametitle{Data} 
% \framesubtitle{Summary Statistics  versus Parameters}
% 
% 
% It is important to distinguish between a population parameter and a
% sample statistic.[.25cm]
% \textbf{A parameter is a numerical summary of a population}.
% Populations consist typically of too many individuals, so that all of them
% can never be observed. For example, it would be nearly impossible to determine
% the average summer earnings of all university students in the US. This would
% require us to identify, find, and question thousands of students. [.25cm]
% It is, however, feasible to select a sample of 100 students (preferably using
% proper randomization) and then the average earning of these 100
% students could be computed. \textbf{Any numerical measure computed
% from a subset of the population} (typically a sample) is a
% \textbf{summary statistic} and can be observed.
% 
% \end{frame}
% 
% 
% %\begin{frame}\frametitle{Data} 
% %\framesubtitle{Summary Statistics  versus Parameters}
% %
% %\textbf{Summary statistics} are numerical summaries (e.g. an average) that
% %are obtained from real
% %data, we can actually observe a \textbf{summary statistic} --- statistics are descriptive. [0.25cm]
% %
% %\textbf{Parameters} are numerical summaries for the entire
% %population that typically remain unknown as we cannot observe the
% %entire population. We will use the information based on the data
% %such as a sample mean to get an idea what the value of the unknown
% %population parameter is --- this process is inferential.
% %
% %
% %\end{frame}
% 
% 
% 
% \begin{frame}
% \frametitle{Data}
% \framesubtitle{Some More Definitions} 
% 
% \begin{definition}{Distribution}
% The distribution of a variable is the collection of possible values the variable can take and how often each value occurs.
% \end{definition}
% 
% \begin{definition}{Frequency Table}
% A frequency table is a summary that shows the distribution of a variable.
% \end{definition}
% 
% \vspace{.25cm} Depending on the type of the data (categorical or
% quantitative) we need to use different graphical and numerical tools
% to analyze and summarize the data at hand.[.15cm]
% 
% We will start by describing data graphically:
% 
% \begin{itemize}
% \item \textbf{bar charts}, \textbf{pie charts} and \textbf{pareto charts} can be used to
% graphically summarize categorical data.
% \item a common graphical display for quantitative data is a \textbf{histogram}.
% \end{itemize}
% 
% \end{frame}
% 


\subsection{Time series}
\begin{frame}
\frametitle{Time series}
Sometimes, variables are \textbf{collected over time.}
\pause
Typically plot these data as a \alert{time series} where time is on the x-axis.

\vspace{0.25cm} \pause

Can you think of an example of a time series?

\pause

Which of the three variables mentioned earlier could qualify as time series?
\end{frame}




\begin{frame}
\frametitle{Example of Time Series Data}
\begin{center}
% \includegraphics[scale=0.35]{Commodity_Futures_Table_Bloomberg.pdf}
% \includegraphics[scale=0.5]{comm_futures_10.png}
\end{center}
\end{frame}


\end{document}
