---
layout: page
title: STAT 486/586
tagline: "Functions"
author: "Jarad Niemi"
date: "`r Sys.Date()`"
output: 
  html_document:
      toc: true
      toc_float: true
---

```{r setup, include=FALSE, purl=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

[R code](11-functions.R)

R is a [functional programming language](https://en.wikipedia.org/wiki/Functional_programming).

```{r}
class(mean)
typeof(mean)
```

If you receive an error about a `closure` this is referring to a function. 

```{r,error=TRUE}
mean[1:3] 
```


# Function basics

## Definition

```{r}
# Create a function
add <- function(x, y) {
  return(x + y)
}
```

```{r}
add(1,2)
add(2,1)
add(x = 1, y = 2)
add(1, y = 2)
add(2, x = 1)
```

## Arguments

```{r}
my_fun <- function(x, y) {
  return(x + y/2)
}
```

```{r}
my_fun(1,2)
my_fun(2,1)
my_fun(x = 1, y = 2)
my_fun(1, y = 2)
my_fun(1, x = 2)
```


```{r}
# Don't do this 
my_fun(x <- 1, y <- 2)
my_fun(1, y <- 2)
my_fun(1, x <- 2)
```

We have actually assigned values to x and y outside the function. 

```{r}
x
y
```


### Default arguments

```{r}
add <- function(x = 1, y = 2) {
  return(x + y)
}
add()
add(x = 9)
add(y = 20)
```



## Generic functions

```{r}
print(mean)
```

Take a look at the help file

```{r}
?mean
```

Notice the words "Generic function". 
This means 







