\documentclass[handout]{beamer}

\input{../frontmatter}
\input{../commands}

\title{M5S1 - Confidence Intervals}

<<options, results='hide', echo=FALSE, purl=FALSE>>=
opts_chunk$set(comment=NA, 
               fig.width=6, fig.height=5, 
               size='small', 
               out.width='0.8\\textwidth', 
               fig.align='center', 
               message=FALSE,
               echo=FALSE,
               cache=FALSE)
options(width=120)
@

<<libraries, message=FALSE, warning=FALSE, cache=FALSE>>=
library("dplyr")
library("ggplot2")
library("xtable")
@

<<set_seed, echo=FALSE>>=
set.seed(2)
@



\begin{document}


\begin{frame}
\titlepage
\end{frame}

\begin{frame}
\frametitle{Outline}

\begin{itemize}
\item Confidence intervals
  \begin{itemize}
  \item Relation to Central Limit Theorem
  \item Based on the Empirical Rule
  \item Finding z critical values
  \item significance level
  \item confidence level
  \item margin of error
  \end{itemize}
\end{itemize}

\end{frame}


\section{Confidence interval for population mean}
\subsection{Central Limit Theorem}
\begin{frame}
\frametitle{Sample mean as an estimator for the population mean}

Recall that due to the CLT, $\overline{X} \stackrel{\cdot}{\sim} N(\mu,\sigma^2/n)$ 
\pause 
where
\begin{itemize}[<+->]
\item $\overline{X} = \frac{1}{n}\sum_{i=1}^n X_i$ is the (random) sample mean,
\item $\mu$ is the population mean,
\item $\sigma^2$ is the population variance, and 
\item $n$ is the sample size.
\end{itemize}

\pause

\alert{Suppose $\mu$ is unknown.}
\pause
Then $\overline{X}$ is an unbiased estimator for $\mu$,
\pause 
since 
\[
E[\overline{X}] = \mu,
\]
\pause
and its variability decreases with increased sample size 
\pause
since 
\[
SD[\overline{X}] = \sqrt{Var[\overline{X}]} = \sigma/\sqrt{n}.
\]
\pause

How can we use this knowledge to describe our uncertainty in $\mu$?

\end{frame}



\begin{frame}
\frametitle{How close is $\overline{X}$ to $\mu$?}
<<fig.height=6, fig.width=10,out.width='\\textwidth', >>=
opar = par(mar=c(6,0,4,0)+0.1)
curve(dnorm, -5, 5, axes=FALSE, frame.plot=TRUE, xlab="", ylab="",
      main="Sampling distribution for sample mean")
axis(1, -3:3,
     expression(mu-3*frac(sigma,sqrt(n)),mu-2*frac(sigma,sqrt(n)),mu-frac(sigma,sqrt(n)),
                mu,
                mu+frac(sigma,sqrt(n)),mu+2*frac(sigma,sqrt(n)),mu+3*frac(sigma,sqrt(n))),
     padj = 1)
xx <- c(-3:-1,1:3)
segments(xx, 0, xx, dnorm(xx), lty=2)
@
\end{frame}


\subsection{Empirical Rule Confidence Intervals}
\begin{frame}
\frametitle{Empirical Rule Confidence Intervals}
\small
From the Central Limit Theorem, we can write
\[ \begin{array}{rl}
P\left( \mu-\phantom{2}\frac{\sigma}{\sqrt{n}} < \overline{X} < \mu+\phantom{2}\frac{\sigma}{\sqrt{n}} \right) &\approx \pause 0.68 \pause \\
P\left( \mu-2\frac{\sigma}{\sqrt{n}} < \overline{X} < \mu+2\frac{\sigma}{\sqrt{n}} \right) &\approx \pause 0.95 \pause \\
P\left( \mu-3\frac{\sigma}{\sqrt{n}} < \overline{X} < \mu+3\frac{\sigma}{\sqrt{n}} \right) &\approx \pause 0.997 \pause \\
\end{array} \]

We can rewrite these inequalities by subtracting $\overline{X}$, 
subtracting $\mu$, and multiplying by -1:
\[ \begin{array}{rl}
P\left( \overline{X}-\phantom{2}\frac{\sigma}{\sqrt{n}} < \mu < \overline{X}+\phantom{2}\frac{\sigma}{\sqrt{n}} \right) &\approx  0.68 \pause \\
P\left( \overline{X}-2\frac{\sigma}{\sqrt{n}} < \mu < \overline{X}+2\frac{\sigma}{\sqrt{n}} \right) &\approx  0.95  \\
P\left( \overline{X}-3\frac{\sigma}{\sqrt{n}} < \mu < \overline{X}+3\frac{\sigma}{\sqrt{n}} \right) &\approx  0.997  \\
\end{array} \]
\pause
We will call these intervals, e.g. $\left(\overline{X}-\frac{\sigma}{\sqrt{n}},\overline{X}+\frac{\sigma}{\sqrt{n}}\right)$, \alert{confidence intervals} and their \alert{confidence level} is the 
probability (usually written as a percentage). 

\end{frame}



\begin{frame}
\frametitle{Example}

US Bank provides students with savings accounts having no monthly maintenance
fee and a low minimum monthly transfer.
\pause
US Bank is interested in knowing the mean monthly balance of all its 
student savings accounts.
\pause
They know the standard deviation of balances is \$20. 
\pause
They take a random sample of 64 student savings accounts and record that at the 
end of the month the sample mean savings was \$105. 
\pause
Construct a 68\% confidence interval for the mean monthly balance. 

\vspace{0.1in} \pause

Let $X_i$ be the end of the month balance for student $i$. 
\pause
Then $E[X_i]=\mu$, the mean monthly balance, is unknown, \pause but $SD[X_i] = \sigma = \$20$ is known. 
\pause 
We obtained a sample of size $n=64$ with a sample mean $\overline{x}=\$105$. 
\pause 
To obtain the 68\% confidence interval for $\mu$, we calculate
\[ \begin{array}{rl} 
\overline{x} \pm \frac{\sigma}{\sqrt{n}} 
&= \pause 
\left(\overline{x} - \frac{\sigma}{\sqrt{n}},\overline{x} + \frac{\sigma}{\sqrt{n}}\right) \pause \\
&=  \left(\$ 105-\frac{\$ 20}{\sqrt{64}}, \$ 105+\frac{\$ 20}{\sqrt{64}}\right) \pause \\
&= \left(\$ 102.5, \$ 107.5\right)
\end{array} 
\]

\end{frame}


\subsection{General Confidence Intervals}
\begin{frame}
\frametitle{Confidence Intervals for $\mu$ when $\sigma$ is known}

\begin{definition}
Let $\mu$ be the population mean and $\sigma$ be the \alert{known} population 
standard deviation. 
\pause
Choose a \alert{significance level} $\alpha$
\pause 
which you can convert to a \alert{confidence level} $C=100(1-\alpha)\%$
\pause
and a \alert{z critical value} $z_{\alpha/2}$ where $P(Z>z_{\alpha/2})=\alpha/2$.
\pause
You obtain a \alert{random sample} of observations from the population and 
calculate the sample mean $\overline{X}$.
\pause 
Then a \alert{$C=100(1-\alpha)$\% confidence interval for $\mu$} is 
\[
\overline{X} \pm z_{\alpha/2} \frac{\sigma}{\sqrt{n}} \pause =
\left(\overline{X} - z_{\alpha/2} \frac{\sigma}{\sqrt{n}}, 
\overline{X} + z_{\alpha/2} \frac{\sigma}{\sqrt{n}}\right)
\]
\pause
where $z_{\alpha/2} \cdot \sigma/\sqrt{n}$ is called the \alert{margin of error}.
\end{definition}
\end{frame}


\begin{frame}
\frametitle{Finding $z$ critical values}
\small

\vspace{-0.1in}

<<fig.width=10>>=
curve(dnorm, -4, 4) 
x<- 1.5
axis(1, x, expression(z[alpha/2]))
xx <- seq(x,5, length=100)
polygon(c(xx,rev(xx)), c(rep(0,length(xx)), dnorm(rev(xx))), col="red", border=NA)
@
\pause
Recall that 
\[ 
P(Z>z_{\alpha/2}) = P(Z<-z_{\alpha/2}).
\]
\pause
Check that 
\[\begin{array}{llll}
C & \alpha & \alpha/2 & z_{\alpha/2} \\
\hline
68\% & 0.32 & 0.16 & \approx 1 \\
95\% & 0.05 & 0.025 & \approx 2 \\
99.7\% & 0.003 & 0.0015 & \approx 3
\end{array}\]
\end{frame}



\begin{frame}
\frametitle{Example}

US Bank provides students with savings accounts having no monthly maintenance
fee and a low minimum monthly transfer.
US Bank is interested in knowing the mean monthly balance of all its 
student savings accounts.
They know the standard deviation of balances is \$20. 
They take a random sample of 64 student savings accounts and record that at the 
end of the month the sample mean savings was \$105. 
Construct a 80\% confidence interval for the mean monthly balance. 

\vspace{0.1in} \pause

Let $X_i$ be the end of the month balance for student $i$. 
Then $E[X_i]=\mu$, the mean monthly balance, is unknown, 
but $SD[X_i] = \sigma = \$20$ is known. 
We obtained a sample of size $n=64$ with a sample mean $\overline{x}=\$105$. 
For a confidence level of 80\%, \pause we have $\alpha=0.2$, \pause
$\alpha/2 = 0.1$ and \pause $z_{\alpha/2} \approx 1.28$. 
\pause
Then we calculate
\[ 
\overline{x} \pm \frac{\sigma}{\sqrt{n}} = \$105 \pm 1.28 \frac{\$20}{\sqrt{64}}
= (\$ 101.8,\$ 108.2)
\]
\pause
which is an 80\% confidence interval for $\mu$

\end{frame}



\end{document}
