---
title: "Midwest Big Data Summer School - Introduction to R Workshop Outline"
author: "Jarad Niemi"
date: "`r Sys.Date()`"
output: rmarkdown::html_document
vignette: >
  %\VignetteIndexEntry{MWBDSS Introduction to R Workshop Outline}
  %\VignetteEngine{knitr::rmarkdown}
---

# Midwest Big Data Summer School
# Introduction to R
# Pre-conference Workshop

## [Introduction to R](01_intro.html)

- [Introduction to R](01_intro.html#intro)
- [Using R as a calculator](01_intro.html#calculator)
- [Reading data into R](01_intro.html#reading)
    - [Reading directly from Excel](01_intro.html#excel)
- [Descriptive statistics](01_intro.html#descriptive)
    - [Subsetting the data](01_intro.html#subsetting)
- [Graphical statistics](01_intro.html#graphical)
- [Getting help](01_intro.html#help)

## [Data Visualization I (ggplot2)](02_graphics.html)

- [Data types](02_graphics.html#types)
- [Data frames](02_graphics.html#frames)
    - [Factors](02_graphics.html#factors)
    - [Dates](02_graphics.html#dates)
- [Reshaping data frames in R](02_graphics.html#reshaping)
- [Aggregating data frames in R](02_graphics.html#aggregating)
- [Basics of ggplot2](02_graphics.html#ggplot2)
- [Customizing (colors, characters, lines)](02_graphics.html#customizing)
- [Getting help on ggplot2](02_graphics.html#help)

## [Data Visualization II (ggplot2)](03_advanced_graphics.html)

- [Workflow](03_advanced_graphics.html#workflow)
- [Workflow for constructing a graph](03_advanced_graphics.html#graph_workflow)
- [Faceting](03_advanced_graphics.html#faceting)
- [Subsetting](03_advanced_graphics.html#subsetting)
- [Making professional graphics](03_advanced_graphics.html#professional)
    - [Exporting graphs](03_advanced_graphics.html#exporting)

## [Intermediate R](04_intermediate_R.html)

- [Exporting tables](04_intermediate_R.html#exporting_tables)
- [Maps](04_intermediate_R.html#maps)
- [Packages](04_intermediate_R.html#packages)
- [Functions](04_intermediate_R.html#functions)
- [R in batch](04_intermediate_R.html#batch)
- [Shiny apps](04_intermediate_R.html#shiny) 
- [Regression](04_intermediate_R.html#regression)
    - [Simple linear regression](04_intermediate_R.html#slr)
    - [Multiple regression](04_intermediate_R.html#multiple_regression)
    - [Smoothing](04_intermediate_R.html#smoothing)
    - [Poisson regression](04_intermediate_R.html#poisson_regression)
    - [Mixed effect models](04_intermediate_R.html#mixed_effect)
    - [Random forests](04_intermediate_R.html#random_forests)
