---
layout: page
title: STAT 486/586
tagline: "Programming in R"
author: "Jarad Niemi"
date: "`r Sys.Date()`"
output: 
  html_document:
      toc: true
      toc_float: true
---

```{r setup, include=FALSE, purl=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

[R code](08-programming.R)



```{r}
library("tidyverse")
```


# Objects

## Data

### Vectors

```{r}
nums <- c(2.5, -3.2, 9, pi, 2, 0.2)
ints <- c(1L, 5L, 99L, 103L)
chrs <- c("my character vector")
lgls <- c(TRUE, FALSE, FALSE, TRUE)
```

#### is.vector()

```{r}
is.vector(nums)
is.vector(ints)
is.vector(chrs)
is.vector(lgls)
```

#### length()

```{r}
length(nums)
length(ints)
length(chrs)
length(lgls)
```

#### typeof()

```{r}
typeof(nums)
typeof(ints)
typeof(chrs)
typeof(lgls)
```

```{r}
ints
typeof(c(1,5,99,103))
```

#### mode()

```{r}
mode(nums)
mode(ints)
mode(chrs)
mode(lgls)
```

#### storage.mode()

```{r}
storage.mode(nums)
storage.mode(ints)
storage.mode(chrs)
storage.mode(lgls)
```



#### class()

```{r}
class(nums)
class(ints)
class(chrs)
class(lgls)
```

[This section in the R manual attempts to disambiguate these different functions](https://stat.ethz.ch/R-manual/R-devel/doc/manual/R-lang.html#Objects).

### Attributes

```{r}
attributes(nums)
```

#### names()

```{r}
names(nums) <- LETTERS[1:length(nums)]
nums
names(nums)
```

```{r}
attributes(nums)
```

#### dim()

```{r}
dim(nums)
```

```{r}
dim(nums) <- c(2,3)
nums
names(nums)
dim(nums)
attributes(nums)
```

```{r}
is.vector(nums)
typeof(nums)
```

### Matrices

```{r}
is.matrix(nums)
colnames(nums) <- LETTERS[1:ncol(nums)]
rownames(nums) <- letters[1:nrow(nums)]
nums
attributes(nums)
typeof(nums)
mode(nums)
storage.mode(nums)
class(nums)
```

### Data.frame

```{r}
nums <- as.data.frame(nums)
is.matrix(nums)
is.data.frame(nums)
nums
attributes(nums)
typeof(nums)
mode(nums)
storage.mode(nums)
class(nums)
```

### List

```{r}
nums <- as.list(nums)
is.data.frame(nums)
is.list(nums)
length(nums)

nums
nums[[1]]
nums$B
attributes(nums)
typeof(nums)
mode(nums)
storage.mode(nums)
class(nums)
```

```{r}
l <- list(
  x = 1:10,
  y = rnorm(10)
)
l$model <- lm(l$y ~ l$x)

l
l$model
attributes(nums)
typeof(nums)
mode(nums)
storage.mode(nums)
class(nums)

attributes(l$model)
```

## Functions

```{r}
attributes(mean)
typeof(mean)
mode(mean)
storage.mode(mean)
class(mean)
```

```{r,error=TRUE}
mean[1:3]
```

# Loops

## for 

## while

## repeat

