---
layout: post
title: "Leroux CAR using CARBayes"
description: ""
category: [Teaching]
tags: [areal,spatial,STAT 615,R,CAR]
---
{% include JB/setup %}

```{r options}
options(width=100)
```

```{r packages}
library("CARBayes")

set.seed(20171109)
sessionInfo()
```

Using the data from [this post](http://www.jarad.me/teaching/2017/11/08/spatial-data), 
we will utilize the intrinsic CAR prior to account for spatial association.

```{r data}
load("data/spatial20171108.rda")
head(d)
```

Build a neighborhood structure based on 4 nearest neighbors, 
i.e. cardinal directions.

```{r neighbors}
distance <- as.matrix(dist(d[,c("x.easting","x.northing")]))

# Proximity matrix
W              <- matrix(0, nrow = n, ncol = n)
W[distance==1] <- 1       	
```

```{r proximity_matrix}
image(W)
```

## Normal model

```{r normal_model}
system.time(
  mn <- S.CARleroux(formula  = Y_normal ~ x1 + x2, 
                   family   = "gaussian", 
                   data     = d,
                   W        = W, 
                   burnin   = 20000, 
                   n.sample = 100000,
                   verbose  = FALSE)
)
```

```{r normal_model_results}
mn
```



## Binomial model

```{r binomial_model}
system.time(
  mb <- S.CARleroux(formula  = Y_binom ~ x1 + x2, 
                   family   = "binomial", 
                   data     = d,
                   trials   = d$trials,
                   W        = W, 
                   burnin   = 20000, 
                   n.sample = 100000,
                   verbose  = FALSE)
)
```

```{r binomial_model_results}
mb
```




## Poisson model

```{r poisson_model}
system.time(
  mp <- S.CARleroux(formula  = Y_pois ~ x1 + x2, 
                   family   = "poisson", 
                   data     = d,
                   W        = W, 
                   burnin   = 20000, 
                   n.sample = 100000,
                   verbose  = FALSE)
)
```

```{r poisson_model_results}
mp
```