---
layout: post
title: "Exponential growth of COVID19 in Des Moines, IA"
description: "All hospital beds gone by June."
category: [News]
tags: [covid19,coronavirus,flattenthecurve]
---

{% include JB/setup %}

[Liz Specht](https://twitter.com/LizSpecht) offers an 
[analysis](https://www.statnews.com/2020/03/10/simple-math-alarming-answers-covid-19/) 
to look at how quickly hospital beds will fill up in the US due to severe 
COVID19 symptoms. Let's perform this analysis for Des Moines. 

## Base assumptions

The 
[assumptions](https://www.statnews.com/2020/03/10/simple-math-alarming-answers-covid-19/) here are that there will be a 

  - doubling of individuals with COVID19 every 6 days,
  - 10% of those individuals will need hospitalization, and
  - hospitalization lasts 3-6 weeks.
  
The details for Des Moines, IA are that 

  - [population is 217,521](https://en.wikipedia.org/wiki/Des_Moines,_Iowa#2010_census), 
  - [Des Moines has 1373 beds](hhttps://www.ahd.com/states/hospital_IA.html), and 
  - 1 individual is sick today (12 March 2020).
  
To be clear, I have no evidence to support that somebody in Ames already has 
COVID19, but people are coming back from international travel 
and Iowa does have 
[13 presumptive positive cases](https://idph.iowa.gov/Emerging-Health-Issues/Novel-Coronavirus), 
most stemming from a single cruise.


  
```{r exponential-growth-Ames, echo=FALSE, message=FALSE, fig.width = 14, fig.cap="Exponential growth of COVID19 in cases and hospitalization in Des Moines, IA."}
library("tidyverse")
date = Sys.Date()
total = 1
hospitalized = 0
for (i in 2:15) {
  date[i] <- date[i-1]+6
  total[i] = total[i-1] * 2
  hospitalized[i] = round(total[i]*0.1)
}

n_beds = 1373

d <- data.frame(date = date,
                total = total,
                hospitalized = hospitalized)
ggplot(d %>% 
         pivot_longer(-date, 
                      names_to = "category", values_to = "count"), 
       aes(date, count, color=category)) + 
  geom_line() + 
  geom_hline(yintercept = n_beds) +
  geom_hline(yintercept = n_beds*0.3, linetype = 2) + 
  labs(title = "Expected COVID19 cases in Des Moines, IA if 1 is sick on 12 Mar 2020") + 
  coord_cartesian(ylim=c(0, n_beds*2)) +
  theme_bw()
```

As Liz Specht suggested, 
if only 30% of beds are available in Des Moines then we run out of beds around 
May 22th. 
If all beds are available, we run out of beds around May 15th. 
If some of these assumptions are off, we run out of hospital beds a couple of 
weeks before or after these predictions.

If 1 person is sick at the Iowa High School Boys Basketball Tournament, 
then we have a [Biogen](https://www.cnn.com/2020/03/11/health/coronavirus-massachusetts-state-of-emergency/index.html) situation on our hands.
At that conference 58% of attendees contracted COVID19. 
If 58% of the attendees at this tournament contract COVID19, 
then we massively accelerate this timeline and hospital beds will be gone 
weeks earlier.

We need to do everything we can to [flatten the curve](https://www.flattenthecurve.com/).
Here is a [list of what you should do](https://www.flattenthecurve.com/#Do).