\documentclass[handout]{beamer}

\usepackage{verbatim,multicol,amsmath}

\input{../../frontmatter}
\input{../../commands}

\title{I10 - Multiple comparisons}

% \newenvironment{remark}[1][Remark]{\begin{trivlist}
% \item[\hskip \labelsep {\bfseries #1}]}{\end{trivlist}}

<<options, results='hide', echo=FALSE, purl=FALSE>>=
opts_chunk$set(comment=NA, 
               fig.width=6, fig.height=4.5, 
               size='tiny', 
               out.width='0.8\\textwidth', 
               fig.align='center', 
               message=FALSE,
               echo=FALSE,
               cache=TRUE)
options(width=120)
@

<<libraries, message=FALSE, warning=FALSE, cache=FALSE>>=
library("tidyverse")
@

<<set_seed, echo=FALSE>>=
set.seed(2)
@

\begin{document}

\begin{frame}
\maketitle
\end{frame}


\section{Multiple Comparisons}
\begin{frame}[fragile]
\frametitle{Mice diet effect on lifetimes}

\small

Female mice were randomly assigned to six treatment groups to investigate 
whether restricting dietary intake increases life expectancy. 
Diet treatments were:

\begin{itemize}
\item NP - mice ate unlimited amount of nonpurified, standard diet
\item N/N85 - mice fed normally before and after weaning. After weaning, ration was controlled at 85 kcal/wk
\item N/R50 - normal diet before weaning and reduced calorie diet (50 kcal/wk) after weaning
\item R/R50 - reduced calorie diet of 50 kcal/wk both before and after weaning
\item N/R50 lopro - normal diet before weaning, restricted diet (50 kcal/wk) after weaning and dietary protein content decreased with advancing age
\item N/R40 - normal diet before weaning and reduced diet (40 Kcal/wk) after weaning.
\end{itemize}

\end{frame}


\begin{frame}[fragile]
\frametitle{Exploratory analysis}

<<data, echo=TRUE>>=
library("Sleuth3")
# head(case0501)
summary(case0501)
case0501 <- case0501 %>% 
  mutate(Diet = factor(Diet, c("NP","N/N85","N/R50","R/R50","lopro","N/R40")),
         Diet = recode(Diet, lopro = "N/R50 lopro"))
case0501 %>% group_by(Diet) %>% summarize(n=n(), mean = mean(Lifetime), sd = sd(Lifetime))
@

\end{frame}



\begin{frame}[fragile]
\frametitle{}

<<data_plot, dependson="data", fig.height=4, echo=TRUE>>=
ggplot(case0501, aes(x=Diet, y=Lifetime)) +
  geom_jitter(width=0.2, height=0) +
  geom_boxplot(fill=NA, color='blue', outlier.color = NA) + 
  coord_flip() +
  theme_bw()
@

\end{frame}


\begin{frame}[fragile]
\frametitle{Are the data compatible with a common mean?}

Let $Y_{ij}$ represent the lifetime of mouse $j$ in diet $i$ for 
$i=1,\ldots,I$ and $j=1,\ldots,n_i$. 
\pause
Assume $Y_{ij} \ind N(\mu_i,\sigma^2)$ and calculate a pvalue for 
$H_0: \mu_i=\mu$ for all $i$. 

\pause 

<<tests, dependson="data", echo=TRUE>>=
bartlett.test(Lifetime ~ Diet, data = case0501)
oneway.test(Lifetime ~ Diet, data = case0501, var.equal = TRUE)
oneway.test(Lifetime ~ Diet, data = case0501, var.equal = FALSE)
@

\end{frame}



\subsection{Statistical testing errors}
\begin{frame}
\frametitle{Statistical testing errors}


\begin{definition}
A \alert{type I error} occurs when a true null hypothesis is rejected.
\end{definition}

\vspace{0.1in} \pause

\begin{definition}
A \alert{type II error} occurs when a false null hypothesis is not rejected. 
\pause 
\alert{Power} is one minus the type II error probability.
\end{definition}

\vspace{0.1in} \pause

We set our significance level $a$ to control the type I error probability. 
\pause 
If we set $a=0.05$, 
then we will incorrectly reject a true null hypothesis 5\% of the time.
\end{frame}



\begin{frame}
\frametitle{Statistical testing errors}

\begin{center}
\begin{tabular}{l|ll}
& \multicolumn{2}{c}{Truth} \\
Decision       & $H_0$ true   & $H_0$ false \\
\hline
$H_0$ not true & Type I error & Correct (power) \\
$H_0$ true     & Correct      & Type II error \\
\hline
\end{tabular}
\end{center}
 
\vspace{0.1in} \pause

\begin{definition}
The \alert{familywise error rate} is the probability of rejecting at least one
true null hypothesis.
\end{definition}

\end{frame}




\begin{frame}
\frametitle{Type I error for all pairwise comparisons of $J$ groups}
  How many combinations when choosing 2 items out of $J$? \pause
	\[ {J\choose 2} \pause = \frac{J!}{2!(J-2)!}. \]
  If $J=6$, then there are 15 different comparison of means. 
  \pause 
  If we set $a=0.05$ as our significance level, 
  then individually each test will only incorrectly reject 5\% of the time.

	\vspace{0.2in} \pause

  If we have 15 tests and use $a=0.05$, what is the familywise error rate? \pause
	\[ 1-(1-0.05)^{15} \pause = 1-(0.95)^{15} = 1-0.46 = 0.54 \]

	\pause

  So there is a greater than 50\% probability of falsely rejecting at least one 
  true null hypothesis!
\end{frame}




\subsection{Bonferroni correction}
\begin{frame}[fragile]
\frametitle{Bonferroni correction}

\begin{definition}
If we do $m$ tests and want the familywise error rate to be $a$, 
the \alert{Bonferroni correction} uses $a/m$ for each individual test. 
\pause 
The familywise error rate, for independent tests, is $1-(1-a/m)^m$.
\end{definition}
\pause
<<echo=FALSE, fig.height=3.5>>=
m = 1:20
plot(m, 1-(1-.05/m)^m, ylim=c(0,0.05), type="l", lwd=2,
     xlab="Number of tests", ylab="Familywise error rate", 
     main="Bonferroni familywise error rate")
lines(m, 1-(1-.01/m)^m, lty=2, col=2, lwd=2)
legend("right", paste("alpha=",c(.05,.01)), lwd=2, lty=1:2, col=1:2)
@
\end{frame}



\begin{frame}[fragile]
\frametitle{Pairwise comparisons}

If we want to consider all pairwise comparisons of the average lifetimes on the
6 diets, we have 15 tests. 
\pause
In order to maintain a familywise error rate of 0.05, 
we need a significance level of 0.05/15 = \Sexpr{0.05/15}.
\pause
<<pairwise, dependson="data", echo=TRUE>>=
pairwise.t.test(case0501$Lifetime, case0501$Diet, p.adjust.method = "none")
@

\end{frame}



\begin{frame}[fragile]
\frametitle{Pairwise comparisons}

If we want to consider all pairwise comparisons of the average lifetimes on the
6 diets, we have 15 tests. 
\pause
Alternatively, you can let R do the adjusting for you, but now you need to 
compare with the original significance level $a$. 
\pause
<<pairwise_bonferroni, dependson="data", echo=TRUE>>=
pairwise.t.test(case0501$Lifetime, case0501$Diet, p.adjust.method = "bonferroni")
@

\end{frame}




\begin{frame}
\frametitle{Comments on the Bonferroni correction}


The Bonferroni correction can be used in any situation. 
\pause 
In particular, it can be used on unadjusted pvalues reported in an article that 
has many tests by comparing their pvalues to $a/m$ where $m$ is the number of 
tests they perform.


\vspace{0.2in} \pause


The Bonferroni correction is (in general) the {\bf most} conservative multiple 
comparison adjustment, i.e. it will lead to the least null hypothesis rejections.


\end{frame}






\subsection{Constructing multiple confidence intervals}
\begin{frame}
\frametitle{Constructing multiple confidence intervals}


A $100(1-a)$\% confidence interval should contain the true value $100(1-a)$\% 
of the time when used with different data sets.


\vspace{0.2in} \pause


An error occurs if the confidence interval does not contain the true value.


\vspace{0.2in} \pause

Just like the Type I error and familywise error rate, 
we can ask what is the probability at least one confidence interval does not 
cover the true value.

\vspace{0.2in} \pause

The procedures we will talk about for confidence intervals have equivalent 
approaches for hypothesis testing (pvalues). 
\pause 
Within these procedures we still have the equivalence between pvalues and CIs.

\end{frame}



\frame{\frametitle{Constructing multiple confidence intervals}
	Confidence interval for the difference between group $j$ and group $j'$:\pause
	\[ \overline{Y}_j - \overline{Y}_{j'} \pm M \,s_p \sqrt{\frac{1}{n_j}+\frac{1}{n_{j'}}} \]
	\pause where $M$ is a multiplier that depends on the adjustment procedure:

	\vspace{0.2in} \pause

	{\small
	\begin{center}
	\begin{tabular}{|l|c|l|}
	\hline
	Procedure & M & \multicolumn{1}{c|}{Use}  \\
	\hline\pause
	LSD & $t_{n-J}(1-a/2)$ & After significant $F$-test \\
	&& (no adjustment) \pause \\
	Dunnett & multivariate $t$ & Compare all groups to control \pause \\
	Tukey-Kramer & $q_{J,n-J}(1-a)/\sqrt{2}$ & All pairwise comparisons \pause \\
	Scheff\'e & $\sqrt{(J-1)F_{(J-1,n-J)}(1-a)}$ & All contrasts \pause \\
	\alert{Bonferroni} & $t_{n-J}(1-(a/m)/2)$ &$m$ tests \\
	&  & (most generic) \\
	\hline
	\end{tabular}
	\end{center}
	}
}


\begin{frame}[fragile]
\frametitle{Tukey for all pairwise comparisons}

<<pairwise_tukey, dependson="data", echo=TRUE>>=
TukeyHSD(aov(Lifetime ~ Diet, data = case0501))
@

\end{frame}



\begin{frame}
\frametitle{False Discovery Rate}


Not wanting to make a single mistake is pretty conservative.


\pause

In high-throughput fields a more common multiple comparison adjustment is false 
discovery rate.

\vspace{0.2in} \pause

\begin{definition}
\alert{False discovery rate} procedures try to control the expected proportion 
of incorrectly rejected null hypotheses.
\end{definition}
\end{frame}


\subsection{Summary}
\begin{frame}
\frametitle{How to incorporate multiple comparison adjustments}

\begin{enumerate}
\item Determine what tests are going to be run (before looking at the data) or 
what confidence intervals are going to be constructed.
\item Determine which multiple comparison adjustment is the most relevant.
\item Use/state that adjustment and interpret your results.
\end{enumerate}

\end{frame}



\end{document}



