######################################################################
#     DO NOT TOUCH: Automatically created using create_Makefile.R
######################################################################

lectures: Ch01.pdf Ch02a.pdf Ch02b.pdf Ch03a.pdf Ch04.pdf Ch05a.pdf Ch05b.pdf Ch06a.pdf Ch07a.pdf Ch07b.pdf Ch10a.pdf Ch10b.pdf Ch11a.pdf Ch11b.pdf Ch11c.pdf Ch11d.pdf Ch14a.pdf Ch14b.pdf Ch15a.pdf Ch15b.pdf Ch16a.pdf Ch16b.pdf 

clean:
	rm -f *.aux *.dvi *.fdb_latexmk *.fls *.log *.nav *.out *.snm *.synctex.gz *.tex *.toc *.vrb
######################################################################

Ch01: Ch01.pdf
Ch01.pdf: Ch01.Rnw
	Rscript -e "library(knitr); knit('Ch01.Rnw')"
	pdflatex Ch01.tex
	pdflatex Ch01.tex

Ch02a: Ch02a.pdf
Ch02a.pdf: Ch02a.Rnw
	Rscript -e "library(knitr); knit('Ch02a.Rnw')"
	pdflatex Ch02a.tex
	pdflatex Ch02a.tex

Ch02b: Ch02b.pdf
Ch02b.pdf: Ch02b.Rnw
	Rscript -e "library(knitr); knit('Ch02b.Rnw')"
	pdflatex Ch02b.tex
	pdflatex Ch02b.tex

Ch03a: Ch03a.pdf
Ch03a.pdf: Ch03a.Rnw
	Rscript -e "library(knitr); knit('Ch03a.Rnw')"
	pdflatex Ch03a.tex
	pdflatex Ch03a.tex

Ch04: Ch04.pdf
Ch04.pdf: Ch04.Rnw
	Rscript -e "library(knitr); knit('Ch04.Rnw')"
	pdflatex Ch04.tex
	pdflatex Ch04.tex

Ch05a: Ch05a.pdf
Ch05a.pdf: Ch05a.Rnw
	Rscript -e "library(knitr); knit('Ch05a.Rnw')"
	pdflatex Ch05a.tex
	pdflatex Ch05a.tex

Ch05b: Ch05b.pdf
Ch05b.pdf: Ch05b.Rnw
	Rscript -e "library(knitr); knit('Ch05b.Rnw')"
	pdflatex Ch05b.tex
	pdflatex Ch05b.tex

Ch06a: Ch06a.pdf
Ch06a.pdf: Ch06a.Rnw
	Rscript -e "library(knitr); knit('Ch06a.Rnw')"
	pdflatex Ch06a.tex
	pdflatex Ch06a.tex

Ch07a: Ch07a.pdf
Ch07a.pdf: Ch07a.Rnw
	Rscript -e "library(knitr); knit('Ch07a.Rnw')"
	pdflatex Ch07a.tex
	pdflatex Ch07a.tex

Ch07b: Ch07b.pdf
Ch07b.pdf: Ch07b.Rnw
	Rscript -e "library(knitr); knit('Ch07b.Rnw')"
	pdflatex Ch07b.tex
	pdflatex Ch07b.tex

Ch10a: Ch10a.pdf
Ch10a.pdf: Ch10a.Rnw
	Rscript -e "library(knitr); knit('Ch10a.Rnw')"
	pdflatex Ch10a.tex
	pdflatex Ch10a.tex

Ch10b: Ch10b.pdf
Ch10b.pdf: Ch10b.Rnw
	Rscript -e "library(knitr); knit('Ch10b.Rnw')"
	pdflatex Ch10b.tex
	pdflatex Ch10b.tex

Ch11a: Ch11a.pdf
Ch11a.pdf: Ch11a.Rnw
	Rscript -e "library(knitr); knit('Ch11a.Rnw')"
	pdflatex Ch11a.tex
	pdflatex Ch11a.tex

Ch11b: Ch11b.pdf
Ch11b.pdf: Ch11b.Rnw
	Rscript -e "library(knitr); knit('Ch11b.Rnw')"
	pdflatex Ch11b.tex
	pdflatex Ch11b.tex

Ch11c: Ch11c.pdf
Ch11c.pdf: Ch11c.Rnw
	Rscript -e "library(knitr); knit('Ch11c.Rnw')"
	pdflatex Ch11c.tex
	pdflatex Ch11c.tex

Ch11d: Ch11d.pdf
Ch11d.pdf: Ch11d.Rnw
	Rscript -e "library(knitr); knit('Ch11d.Rnw')"
	pdflatex Ch11d.tex
	pdflatex Ch11d.tex

Ch14a: Ch14a.pdf
Ch14a.pdf: Ch14a.Rnw
	Rscript -e "library(knitr); knit('Ch14a.Rnw')"
	pdflatex Ch14a.tex
	pdflatex Ch14a.tex

Ch14b: Ch14b.pdf
Ch14b.pdf: Ch14b.Rnw
	Rscript -e "library(knitr); knit('Ch14b.Rnw')"
	pdflatex Ch14b.tex
	pdflatex Ch14b.tex

Ch15a: Ch15a.pdf
Ch15a.pdf: Ch15a.Rnw
	Rscript -e "library(knitr); knit('Ch15a.Rnw')"
	pdflatex Ch15a.tex
	pdflatex Ch15a.tex

Ch15b: Ch15b.pdf
Ch15b.pdf: Ch15b.Rnw
	Rscript -e "library(knitr); knit('Ch15b.Rnw')"
	pdflatex Ch15b.tex
	pdflatex Ch15b.tex

Ch16a: Ch16a.pdf
Ch16a.pdf: Ch16a.Rnw
	Rscript -e "library(knitr); knit('Ch16a.Rnw')"
	pdflatex Ch16a.tex
	pdflatex Ch16a.tex

Ch16b: Ch16b.pdf
Ch16b.pdf: Ch16b.Rnw
	Rscript -e "library(knitr); knit('Ch16b.Rnw')"
	pdflatex Ch16b.tex
	pdflatex Ch16b.tex

