PROBABILITY := \
  Probability/P1-Probability/P1-Probability.pdf \
  Probability/P2-Discrete_distributions/P2-Discrete_distributions.pdf \
  Probability/P3-Continuous_distributions/P3-Continuous_distributions.pdf \
  Probability/P4-Central_limit_theorem/P4-Central_Limit_Theorem.pdf \
  Probability/P5-Multiple_random_variables/P5-Multiple_random_variables.pdf \
  Probability/Distributions/Exponential/Exponential.pdf \
  Probability/Distributions/Gamma/Gamma.pdf \
  Probability/Distributions/Inverse_gamma/Inverse_gamma.pdf \
  Probability/Distributions/Students_t/Students_t.pdf

probability.pdf: $(PROBABILITY)
	gs -q -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -sOutputFile=probability.pdf $(PROBABILITY)


